import type { NationDef, FactionDef, CorporationDef, InstitutionDef, CompetencyDef } from '../types';

// Ideology axes shared by factions, nations, characters and laws.
export const AXES = ['Federal ↔ Sovereign', 'Expansion ↔ Preservation', 'Market ↔ Public', 'Enhancement ↔ Baseline', 'Machine ↔ Human', 'Security ↔ Liberty', 'Autonomy ↔ Central'];
export const AXIS_SHORT = ['federal', 'expansion', 'market', 'enhancement', 'machine', 'security', 'autonomy'];
export const AX = { FED: 0, EXP: 1, MKT: 2, ENH: 3, MAC: 4, SEC: 5, AUT: 6 } as const;

export const FACTIONS: FactionDef[] = [
  { id: 'federalists', name: 'Federalists', short: 'FED', color: '#4da3ff', axes: [0.85, 0.2, 0, 0, 0.1, 0.1, -0.3], initiallyActive: true, description: 'Want stronger common institutions, deeper integration and a UNE that can act decisively for humanity.' },
  { id: 'sovereigntists', name: 'Sovereigntists', short: 'SOV', color: '#9aa7b8', axes: [-0.85, 0, 0.15, -0.1, 0, 0.25, 0.1], initiallyActive: true, description: 'Defend the member states as the rightful seat of sovereignty, and resist every transfer of power to the UNE.' },
  { id: 'expansionists', name: 'Expansionists', short: 'EXP', color: '#ff9f43', axes: [0.2, 0.9, 0.3, 0.2, 0.2, 0, 0.1], initiallyActive: true, description: 'Want settlement as fast as possible. Humanity\'s future is in space, and every delay costs it.' },
  { id: 'preservationists', name: 'Preservationists', short: 'PRS', color: '#5fd38a', axes: [0.25, -0.85, -0.3, -0.2, -0.1, -0.2, 0], initiallyActive: true, description: 'Put Earth\'s biosphere, planetary protection and restraint before exploitation of other worlds.' },
  { id: 'industrialists', name: 'Industrialists', short: 'IND', color: '#ffb35c', axes: [0, 0.6, 0.55, 0.1, 0.45, 0.1, -0.1], initiallyActive: true, description: 'Want aggressive resource development, heavy industry and infrastructure at scale.' },
  { id: 'labor', name: 'Labor Coalition', short: 'LAB', color: '#e86a6a', axes: [0.2, 0, -0.85, -0.1, -0.6, 0, 0.1], initiallyActive: true, description: 'Represents working people: wages, safety, and the social cost of automation.' },
  { id: 'science', name: 'Scientific Governance Movement', short: 'SCI', color: '#b98cff', axes: [0.45, 0.3, -0.1, 0.3, 0.3, -0.2, 0], initiallyActive: true, description: 'Wants evidence-driven policy, expert institutions and open science.' },
  { id: 'corporate', name: 'Corporate Coalition', short: 'CRP', color: '#ffd84d', axes: [-0.2, 0.5, 0.9, 0.2, 0.45, 0.1, 0], initiallyActive: true, description: 'Voice of the commercial space sector: property rights, low taxes and light regulation.' },
  { id: 'colonial', name: 'Colonial Autonomists', short: 'COL', color: '#ff7ac8', axes: [-0.3, 0.3, 0.1, 0.1, 0, -0.3, 0.95], initiallyActive: false, description: 'Want self-rule for the worlds beyond Earth. No taxation or law without consent.' },
  { id: 'solarFederalists', name: 'Solar Federalists', short: 'SLF', color: '#6ee7ff', axes: [0.7, 0.5, 0, 0.1, 0.1, 0, 0.5], initiallyActive: false, description: 'Want one federation of all worlds, with full and equal representation for every citizen wherever they were born.' },
  { id: 'transhumanists', name: 'Transhumanists', short: 'TRH', color: '#c4f25a', axes: [0.1, 0.4, 0.3, 0.95, 0.5, -0.2, 0.2], initiallyActive: false, description: 'See biological enhancement as a right and a necessity for living beyond Earth.' },
  { id: 'humanPreservation', name: 'Human Preservation Movement', short: 'HPM', color: '#d9c7a0', axes: [0, -0.3, -0.1, -0.95, -0.5, 0.2, 0], initiallyActive: false, description: 'Oppose radical biological alteration and defend a shared human nature.' },
  { id: 'machineIntegration', name: 'Machine Integration Movement', short: 'MIM', color: '#7cf0c8', axes: [0.2, 0.3, 0.2, 0.4, 0.95, -0.1, 0.1], initiallyActive: false, description: 'Want AI given a growing role in governance and economy, and machine minds given recognition.' },
  { id: 'decentralists', name: 'Decentralists', short: 'DEC', color: '#a0e0a0', axes: [-0.6, 0.1, 0.2, 0.1, 0.1, -0.6, 0.6], initiallyActive: true, description: 'Favor distributed governance, local control and networks instead of hierarchies.' },
  { id: 'security', name: 'Security Bloc', short: 'SEC', color: '#ff5c5c', axes: [0.3, 0.1, 0.1, 0, 0.2, 0.9, -0.5], initiallyActive: true, description: 'Put defense, stability and order first in a dangerous Solar System.' },
];

const fs = (fed: number, sov: number, exp: number, pres: number, ind: number, lab: number, sci: number, corp: number, dec: number, sec: number) => ({
  federalists: fed, sovereigntists: sov, expansionists: exp, preservationists: pres, industrialists: ind, labor: lab, science: sci, corporate: corp, decentralists: dec, security: sec,
});

export const NATIONS: NationDef[] = [
  { id: 'usa', name: 'United States of America', short: 'USA', color: '#3d7bd9', states: 1, description: 'The largest space economy on Earth, with a deep private launch sector and a political culture wary of supranational authority.', population: 365e6, gdp: 42e12, baseGrowth: 0.018, popGrowth: 0.004, science: 380, launchCapacity: 9000, military: 100, debtRatio: 1.3, ideology: [], publicOpinion: 0.52, uneSupport: 0.55, integrationPref: -0.1, stability: 0.72, spaceBudgetShare: 0.0016, energyTW: 3.4, factionSupport: fs(0.08, 0.16, 0.14, 0.1, 0.1, 0.1, 0.08, 0.12, 0.06, 0.06), nameCulture: 'american', leadershipCycle: 4 },
  { id: 'eu', name: 'European Union', short: 'EU', color: '#5b6fe0', states: 27, description: 'A union of 27 states and the Compact\'s strongest champion of pooled sovereignty. Its space industry is strong but fragmented.', population: 440e6, gdp: 30e12, baseGrowth: 0.013, popGrowth: -0.001, science: 320, launchCapacity: 2200, military: 55, debtRatio: 0.95, ideology: [], publicOpinion: 0.62, uneSupport: 0.7, integrationPref: 0.5, stability: 0.78, spaceBudgetShare: 0.0007, energyTW: 2.2, factionSupport: fs(0.18, 0.1, 0.08, 0.16, 0.06, 0.14, 0.12, 0.06, 0.05, 0.05), nameCulture: 'european', leadershipCycle: 5 },
  { id: 'chn', name: "People's Republic of China", short: 'CHN', color: '#d94b4b', states: 1, description: 'An industrial superpower with an ambitious state-led lunar program and a vast manufacturing base.', population: 1330e6, gdp: 45e12, baseGrowth: 0.028, popGrowth: -0.004, science: 400, launchCapacity: 7000, military: 90, debtRatio: 0.9, ideology: [], publicOpinion: 0.55, uneSupport: 0.58, integrationPref: 0, stability: 0.8, spaceBudgetShare: 0.0013, energyTW: 5.5, factionSupport: fs(0.1, 0.18, 0.16, 0.06, 0.18, 0.08, 0.1, 0.04, 0.03, 0.07), nameCulture: 'chinese', leadershipCycle: 5 },
  { id: 'ind', name: 'Republic of India', short: 'IND', color: '#ff9933', states: 1, description: 'The world\'s most populous state and a fast-growing space power, balancing development at home against ambitions beyond Earth.', population: 1650e6, gdp: 20e12, baseGrowth: 0.045, popGrowth: 0.004, science: 170, launchCapacity: 1800, military: 60, debtRatio: 0.8, ideology: [], publicOpinion: 0.6, uneSupport: 0.62, integrationPref: 0.15, stability: 0.7, spaceBudgetShare: 0.0006, energyTW: 2.4, factionSupport: fs(0.1, 0.16, 0.12, 0.08, 0.12, 0.16, 0.1, 0.06, 0.04, 0.06), nameCulture: 'indian', leadershipCycle: 5 },
  { id: 'jpn', name: 'Japan', short: 'JPN', color: '#e05a8a', states: 1, description: 'A technological leader in robotics and precision manufacturing, facing a shrinking population.', population: 112e6, gdp: 6.2e12, baseGrowth: 0.008, popGrowth: -0.006, science: 110, launchCapacity: 900, military: 30, debtRatio: 2.3, ideology: [], publicOpinion: 0.6, uneSupport: 0.66, integrationPref: 0.3, stability: 0.82, spaceBudgetShare: 0.0006, energyTW: 0.55, factionSupport: fs(0.12, 0.1, 0.1, 0.1, 0.14, 0.1, 0.16, 0.08, 0.04, 0.06), nameCulture: 'japanese', leadershipCycle: 4 },
  { id: 'rus', name: 'Russian Federation', short: 'RUS', color: '#8a6cd9', states: 1, description: 'A pioneering spacefaring nation with deep engineering traditions and strong reservations about federal authority.', population: 135e6, gdp: 3.5e12, baseGrowth: 0.012, popGrowth: -0.003, science: 50, launchCapacity: 900, military: 55, debtRatio: 0.3, ideology: [], publicOpinion: 0.42, uneSupport: 0.44, integrationPref: -0.4, stability: 0.62, spaceBudgetShare: 0.0009, energyTW: 0.9, factionSupport: fs(0.06, 0.24, 0.12, 0.06, 0.14, 0.1, 0.08, 0.04, 0.04, 0.12), nameCulture: 'russian', leadershipCycle: 6 },
  { id: 'bra', name: 'Federative Republic of Brazil', short: 'BRA', color: '#2fbf71', states: 1, description: 'An equatorial launch power and a voice for the developing world in Compact politics.', population: 225e6, gdp: 4.2e12, baseGrowth: 0.022, popGrowth: 0.001, science: 30, launchCapacity: 250, military: 18, debtRatio: 0.9, ideology: [], publicOpinion: 0.6, uneSupport: 0.62, integrationPref: 0.2, stability: 0.66, spaceBudgetShare: 0.0003, energyTW: 0.45, factionSupport: fs(0.12, 0.12, 0.08, 0.16, 0.1, 0.16, 0.08, 0.08, 0.05, 0.05), nameCulture: 'brazilian', leadershipCycle: 4 },
  { id: 'idn', name: 'Republic of Indonesia', short: 'IDN', color: '#e34d4d', states: 1, description: 'An archipelagic giant with an equatorial spaceport and a rapidly growing middle class.', population: 310e6, gdp: 5.2e12, baseGrowth: 0.04, popGrowth: 0.004, science: 28, launchCapacity: 150, military: 16, debtRatio: 0.5, ideology: [], publicOpinion: 0.62, uneSupport: 0.64, integrationPref: 0.15, stability: 0.68, spaceBudgetShare: 0.0002, energyTW: 0.5, factionSupport: fs(0.12, 0.14, 0.08, 0.14, 0.12, 0.14, 0.08, 0.06, 0.06, 0.06), nameCulture: 'indonesian', leadershipCycle: 5 },
  { id: 'afu', name: 'African Union', short: 'AFU', color: '#f2b233', states: 55, description: 'Fifty-five states and a quarter of humanity. Its population is the youngest on Earth and its economic growth among the fastest.', population: 2300e6, gdp: 12e12, baseGrowth: 0.05, popGrowth: 0.018, science: 60, launchCapacity: 300, military: 30, debtRatio: 0.6, ideology: [], publicOpinion: 0.68, uneSupport: 0.7, integrationPref: 0.45, stability: 0.58, spaceBudgetShare: 0.0002, energyTW: 1.6, factionSupport: fs(0.18, 0.12, 0.06, 0.14, 0.12, 0.16, 0.08, 0.04, 0.05, 0.05), nameCulture: 'african', leadershipCycle: 5 },
  { id: 'kor', name: 'Republic of Korea', short: 'KOR', color: '#4fc3f7', states: 1, description: 'A semiconductor and shipbuilding powerhouse with a growing launch industry.', population: 49e6, gdp: 3.2e12, baseGrowth: 0.012, popGrowth: -0.006, science: 70, launchCapacity: 600, military: 25, debtRatio: 0.7, ideology: [], publicOpinion: 0.6, uneSupport: 0.64, integrationPref: 0.25, stability: 0.8, spaceBudgetShare: 0.0008, energyTW: 0.4, factionSupport: fs(0.12, 0.1, 0.12, 0.08, 0.14, 0.12, 0.14, 0.1, 0.03, 0.05), nameCulture: 'korean', leadershipCycle: 5 },
  { id: 'gbr', name: 'United Kingdom', short: 'GBR', color: '#c94f7c', states: 1, description: 'A financial and scientific center with outsized influence in space law and finance.', population: 70e6, gdp: 4.5e12, baseGrowth: 0.014, popGrowth: 0.003, science: 70, launchCapacity: 400, military: 25, debtRatio: 1.1, ideology: [], publicOpinion: 0.52, uneSupport: 0.56, integrationPref: 0, stability: 0.76, spaceBudgetShare: 0.0005, energyTW: 0.28, factionSupport: fs(0.1, 0.16, 0.1, 0.12, 0.08, 0.14, 0.12, 0.08, 0.05, 0.05), nameCulture: 'british', leadershipCycle: 5 },
  { id: 'mec', name: 'Middle East Council', short: 'MEC', color: '#26a69a', states: 14, description: 'A cooperation council of fourteen states investing sovereign wealth into energy, launch and orbital industry.', population: 420e6, gdp: 7e12, baseGrowth: 0.025, popGrowth: 0.012, science: 40, launchCapacity: 400, military: 45, debtRatio: 0.5, ideology: [], publicOpinion: 0.5, uneSupport: 0.52, integrationPref: -0.2, stability: 0.6, spaceBudgetShare: 0.0004, energyTW: 1.4, factionSupport: fs(0.1, 0.18, 0.12, 0.08, 0.14, 0.1, 0.1, 0.08, 0.04, 0.06), nameCulture: 'arabic', leadershipCycle: 6 },
  { id: 'lac', name: 'Latin American & Caribbean Community', short: 'LAC', color: '#7cb342', states: 32, description: 'Thirty-two states coordinating their Compact votes, with strong commitments to common heritage and environmental protection.', population: 520e6, gdp: 7.5e12, baseGrowth: 0.022, popGrowth: 0.004, science: 30, launchCapacity: 150, military: 15, debtRatio: 0.8, ideology: [], publicOpinion: 0.6, uneSupport: 0.62, integrationPref: 0.3, stability: 0.64, spaceBudgetShare: 0.0002, energyTW: 0.9, factionSupport: fs(0.14, 0.12, 0.06, 0.16, 0.1, 0.18, 0.08, 0.06, 0.05, 0.05), nameCulture: 'latin', leadershipCycle: 5 },
  { id: 'apg', name: 'Asia-Pacific Group', short: 'APG', color: '#ab47bc', states: 22, description: 'A diverse caucus of South, Southeast Asian and Pacific states, from megacities to atoll nations threatened by rising seas.', population: 1350e6, gdp: 10e12, baseGrowth: 0.035, popGrowth: 0.006, science: 70, launchCapacity: 400, military: 45, debtRatio: 0.7, ideology: [], publicOpinion: 0.58, uneSupport: 0.6, integrationPref: 0.15, stability: 0.66, spaceBudgetShare: 0.0003, energyTW: 1.6, factionSupport: fs(0.12, 0.14, 0.1, 0.12, 0.12, 0.14, 0.1, 0.06, 0.05, 0.05), nameCulture: 'asianPacific', leadershipCycle: 5 },
  { id: 'oms', name: 'Other Member States', short: 'OMS', color: '#90a4ae', states: 35, description: 'Thirty-five states outside the major blocs, including Canada, Türkiye, Ukraine, Norway and Switzerland, voting in a shifting caucus.', population: 350e6, gdp: 9e12, baseGrowth: 0.02, popGrowth: 0.003, science: 90, launchCapacity: 600, military: 40, debtRatio: 0.7, ideology: [], publicOpinion: 0.56, uneSupport: 0.58, integrationPref: 0.1, stability: 0.7, spaceBudgetShare: 0.0005, energyTW: 1.2, factionSupport: fs(0.14, 0.12, 0.1, 0.14, 0.1, 0.12, 0.12, 0.06, 0.05, 0.05), nameCulture: 'mixed', leadershipCycle: 5 },
];

export const CORPORATIONS: CorporationDef[] = [
  { id: 'argent', name: 'Argent Launch Systems', short: 'ARG', sector: 'launch', home: 'usa', structure: 'public', color: '#c0c7d1', cash: 3.5e10, influence: 0.5, reputation: 0.7, focus: ['logistics', 'launch'], riskAppetite: 0.6, description: 'The dominant heavy-lift operator, flying reusable super-heavy launchers from four continents.' },
  { id: 'longwei', name: 'Longwei Aerospace Group', short: 'LWA', sector: 'habitat', home: 'chn', structure: 'state-owned', color: '#e3584f', cash: 3.0e10, influence: 0.45, reputation: 0.65, focus: ['habitat', 'logistics', 'mining'], riskAppetite: 0.5, description: 'A state-owned enterprise that builds stations, landers and lunar infrastructure.' },
  { id: 'selenic', name: 'Selenic Mining Consortium', short: 'SMC', sector: 'mining', home: 'eu', structure: 'public', color: '#9fd3c7', cash: 1.2e10, influence: 0.3, reputation: 0.6, focus: ['mining', 'processing'], riskAppetite: 0.7, description: 'A Luxembourg-listed miner betting everything on lunar water and asteroid metals.' },
  { id: 'kaneshiro', name: 'Kaneshiro Heavy Industries', short: 'KHI', sector: 'manufacturing', home: 'jpn', structure: 'family', color: '#f28b50', cash: 2.2e10, influence: 0.35, reputation: 0.75, focus: ['manufacturing', 'energy', 'shipyard'], riskAppetite: 0.4, description: 'A century-old family conglomerate of shipyards, reactors and industrial robots.' },
  { id: 'vyoma', name: 'Vyoma Orbital', short: 'VYO', sector: 'logistics', home: 'ind', structure: 'ppp', color: '#ffb74d', cash: 8.0e9, influence: 0.25, reputation: 0.65, focus: ['logistics', 'science'], riskAppetite: 0.65, description: 'A public-private partnership running low-cost tugs, satellites and cislunar freight.' },
  { id: 'terranova', name: 'Terra Nova Habitat Cooperative', short: 'TNC', sector: 'habitat', home: 'bra', structure: 'cooperative', color: '#8bc34a', cash: 5.0e9, influence: 0.2, reputation: 0.8, focus: ['habitat', 'lifeSupport', 'food'], riskAppetite: 0.5, description: 'A worker-owned builder of habitats, farms and life-support systems.' },
  { id: 'solaris', name: 'Solaris Power Holdings', short: 'SPH', sector: 'energy', home: 'mec', structure: 'public', color: '#ffe066', cash: 1.8e10, influence: 0.35, reputation: 0.6, focus: ['energy'], riskAppetite: 0.55, description: 'A sovereign-wealth-backed energy major pivoting toward space solar power.' },
];

// Templates for corporations founded later in the campaign.
export const CORP_TEMPLATES: { sector: string; names: string[]; focus: string[]; tech?: string }[] = [
  { sector: 'mining', names: ['Ceres Extraction Company', 'Dark Rock Resources', 'Vesta Metals', 'Psyche Ferrous', 'Belt Holdings'], focus: ['mining', 'processing'], tech: 'asteroid_mining' },
  { sector: 'energy', names: ['Helion Fusion', 'Tokamak Industries', 'Sunforge Energy', 'Photon Grid Corporation'], focus: ['energy'], tech: 'fusion_power' },
  { sector: 'manufacturing', names: ['Orbital Fabrication Works', 'Lagrange Industrial', 'Mare Foundry', 'Tharsis Heavy Industry'], focus: ['manufacturing', 'processing'], tech: 'space_machine_tools' },
  { sector: 'habitat', names: ['Cylinder Estates', 'Halo Habitats', 'Aerostat Living', 'Torus Development Trust'], focus: ['habitat', 'lifeSupport'], tech: 'rotating_habitats' },
  { sector: 'logistics', names: ['Hohmann Freight', 'Cycler Lines', 'Ecliptic Shipping', 'Solar Express'], focus: ['logistics'], tech: 'nuclear_thermal_propulsion' },
  { sector: 'ai', names: ['Deep Mind Collective', 'Axiom Cognition', 'Lattice Intelligence'], focus: ['science', 'manufacturing'], tech: 'industrial_ai' },
  { sector: 'dyson', names: ['Helios Collective', 'Mercury Industrial Trust', 'Stellar Harvest'], focus: ['dyson', 'energy'], tech: 'dyson_collectors' },
  { sector: 'biotech', names: ['Helix Life Systems', 'Gaia Bioworks', 'Genesis Biologics'], focus: ['food', 'lifeSupport'], tech: 'cellular_agriculture' },
];

export const INSTITUTIONS: InstitutionDef[] = [
  { id: 'secretariat', name: 'UNE General Secretariat', short: 'SEC', description: 'The administrative core of the UNE. It drives federal capacity and political capital.', baseFunding: 8e9, initiallyActive: true, role: 'administration' },
  { id: 'chamberNations', name: 'Chamber of Nations', short: 'CoN', description: 'The upper house, where member states are represented.', baseFunding: 1e9, initiallyActive: true, role: 'legislature' },
  { id: 'assembly', name: 'Assembly of Humanity', short: 'AoH', description: 'The directly elected lower house of citizens.', baseFunding: 2e9, initiallyActive: true, role: 'legislature' },
  { id: 'court', name: 'Earth Compact Court', short: 'ECC', description: 'The constitutional and intergovernmental court. It supports constitutional stability and rules on disputes.', baseFunding: 1e9, initiallyActive: true, role: 'judiciary' },
  { id: 'sda', name: 'Solar Development Authority', short: 'SDA', description: 'Coordinates space settlement and infrastructure. It reduces construction costs and founds UNE settlements.', baseFunding: 1.2e10, initiallyActive: true, role: 'development' },
  { id: 'pdc', name: 'Planetary Defense Command', short: 'PDC', description: 'Tracks and responds to astronomical threats. It drives survey coverage and deflection readiness.', baseFunding: 5e9, initiallyActive: true, role: 'defense' },
  { id: 'icc', name: 'Interplanetary Commerce Commission', short: 'ICC', description: 'Regulates off-world commerce, collects royalties and levies, and restrains market abuse.', baseFunding: 2e9, initiallyActive: true, role: 'regulation' },
  { id: 'isd', name: 'International Science Directorate', short: 'ISD', description: 'Coordinates strategic research. Its budget is converted into research points.', baseFunding: 2e10, initiallyActive: true, role: 'science' },
  { id: 'sia', name: 'Solar Infrastructure Authority', short: 'SIA', description: 'Operates UNE-owned strategic infrastructure, fleets and depots.', baseFunding: 4e9, initiallyActive: true, role: 'infrastructure' },
  { id: 'bank', name: 'UNE Development Bank', short: 'UDB', description: 'Finances long-duration projects. It lowers borrowing costs and lends to settlements.', baseFunding: 1.5e9, initiallyActive: true, role: 'finance' },
  { id: 'etsa', name: 'Extraterrestrial Settlement Authority', short: 'ETSA', description: 'Administers UNE territories. It affects colonial sentiment and territorial administration.', baseFunding: 3e9, initiallyActive: true, role: 'territories' },
  { id: 'osa', name: 'Orbital Safety Authority', short: 'OSA', description: 'Regulates traffic and debris mitigation around Earth and beyond.', baseFunding: 2.5e9, initiallyActive: true, role: 'safety' },
  // Institutions that may be created during the campaign
  { id: 'securityForces', name: 'UNE Security Forces', short: 'USF', description: 'The federal security service: patrols, counter-piracy and crisis response.', baseFunding: 8e9, initiallyActive: false, role: 'security' },
  { id: 'energyTrust', name: 'Solar Energy Trust', short: 'SET', description: 'Holds a common share of Helios swarm output in trust for all citizens.', baseFunding: 2e9, initiallyActive: false, role: 'energy' },
  { id: 'mercuryAuthority', name: 'Mercury Industrial Authority', short: 'MIA', description: 'Governs extraction, mass drivers and collector production on Mercury.', baseFunding: 5e9, initiallyActive: false, role: 'industry' },
  { id: 'councilWorlds', name: 'Council of Worlds', short: 'CoW', description: 'Upper house representing the political units of the Solar System.', baseFunding: 2e9, initiallyActive: false, role: 'legislature' },
  { id: 'aiBoard', name: 'AI Oversight Board', short: 'AIB', description: 'Licenses and audits autonomous systems and artificial minds.', baseFunding: 1.5e9, initiallyActive: false, role: 'regulation' },
];

export const COMPETENCIES: CompetencyDef[] = [
  // Exclusive
  { id: 'extraterrestrialClaims', name: 'Extraterrestrial sovereignty claims', group: 'exclusive', initial: 'exclusive', description: 'Only the UNE may recognize territorial claims beyond Earth.' },
  { id: 'interplanetaryLaw', name: 'Interplanetary territorial law', group: 'exclusive', initial: 'exclusive', description: 'Law governing extraterrestrial territories and property.' },
  { id: 'orbitalNavigation', name: 'Orbital navigation standards', group: 'exclusive', initial: 'exclusive', description: 'Traffic rules, frequencies and navigation standards.' },
  { id: 'planetaryDefense', name: 'Planetary defense', group: 'exclusive', initial: 'exclusive', description: 'Detection and deflection of hazardous objects.' },
  { id: 'deepSpaceComms', name: 'Deep-space communications standards', group: 'exclusive', initial: 'exclusive', description: 'The common interplanetary network.' },
  { id: 'settlementRegistration', name: 'Registration of off-world settlements', group: 'exclusive', initial: 'exclusive', description: 'Large settlements must be registered and chartered by the UNE.' },
  { id: 'weaponsRegulation', name: 'Extraterrestrial weapons regulation', group: 'exclusive', initial: 'exclusive', description: 'Arms control beyond Earth.' },
  { id: 'disputeArbitration', name: 'Interplanetary dispute arbitration', group: 'exclusive', initial: 'exclusive', description: 'Binding arbitration of disputes between actors off Earth.' },
  // Shared
  { id: 'spaceIndustry', name: 'Space industrial development', group: 'shared', initial: 'shared', description: 'Industrial policy for extraterrestrial development.' },
  { id: 'corporateRegulation', name: 'Corporate regulation', group: 'shared', initial: 'shared', description: 'Antitrust, IP and charters for space corporations.' },
  { id: 'research', name: 'Scientific research', group: 'shared', initial: 'shared', description: 'Common research programs and science policy.' },
  { id: 'energyInfrastructure', name: 'Energy infrastructure', group: 'shared', initial: 'shared', description: 'Space power, beamed energy and grids.' },
  { id: 'environment', name: 'Environmental protection', group: 'shared', initial: 'shared', description: 'Climate coordination and planetary protection.' },
  { id: 'offworldMigration', name: 'Off-world migration', group: 'shared', initial: 'shared', description: 'Migration to and between settlements.' },
  { id: 'transportSystems', name: 'Major transportation systems', group: 'shared', initial: 'shared', description: 'Launch, freight and interplanetary transport.' },
  { id: 'resourcePolicy', name: 'Strategic resource policy', group: 'shared', initial: 'shared', description: 'Royalties, reserves and resource regimes.' },
  { id: 'offworldHealthcare', name: 'Extraterrestrial healthcare', group: 'shared', initial: 'shared', description: 'Health standards in settlements.' },
  // Limited / reserved
  { id: 'directTaxation', name: 'Direct taxation', group: 'reserved', initial: 'limited', description: 'Power to tax corporations and citizens directly.' },
  { id: 'militaryCommand', name: 'Military command', group: 'reserved', initial: 'limited', description: 'Command of armed forces beyond planetary defense.' },
  { id: 'citizenship', name: 'Citizenship', group: 'reserved', initial: 'national', description: 'Who is a citizen, and of what.' },
  { id: 'education', name: 'Education', group: 'reserved', initial: 'national', description: 'Schools and universities.' },
  { id: 'healthcare', name: 'Healthcare on Earth', group: 'reserved', initial: 'national', description: 'Domestic health systems.' },
  { id: 'criminalLaw', name: 'Criminal law', group: 'reserved', initial: 'national', description: 'Ordinary criminal law and policing.' },
  { id: 'welfare', name: 'Welfare and housing', group: 'reserved', initial: 'national', description: 'Social protection on Earth.' },
];

export const LEVEL_RANK: Record<string, number> = { national: 0, limited: 1, shared: 2, exclusive: 3 };
export const LEVELS = ['national', 'limited', 'shared', 'exclusive'] as const;

export const FACTION: Record<string, FactionDef> = Object.fromEntries(FACTIONS.map((f) => [f.id, f]));
export const NATION: Record<string, NationDef> = Object.fromEntries(NATIONS.map((n) => [n.id, n]));
export const INSTITUTION: Record<string, InstitutionDef> = Object.fromEntries(INSTITUTIONS.map((i) => [i.id, i]));
export const COMPETENCY: Record<string, CompetencyDef> = Object.fromEntries(COMPETENCIES.map((c) => [c.id, c]));
