import type { ComponentDef, StructureDef } from '../types';

export const STRUCTURES: StructureDef[] = [
  { id: 'aluminium', name: 'Aluminium-Lithium Truss', massFraction: 0.12, costMult: 1.0, reliability: 0.998, goods: { alloys: 1 }, description: 'Proven and cheap to build.' },
  { id: 'steel', name: 'Stainless Steel Hull', massFraction: 0.17, costMult: 0.75, reliability: 0.999, goods: { alloys: 1 }, description: 'Heavy but tough, thermally robust and cheap.' },
  { id: 'titanium', name: 'Titanium Frame', massFraction: 0.095, costMult: 1.5, reliability: 0.998, goods: { alloys: 1 }, description: 'Strong, light and expensive.' },
  { id: 'composite', name: 'Carbon Composite Structure', massFraction: 0.07, costMult: 1.9, reliability: 0.997, goods: { composites: 1 }, tech: 'advanced_composites', description: 'A very light structure that needs a mature chemical industry.' },
  { id: 'nanotube', name: 'Nanotube-Graphene Lattice', massFraction: 0.035, costMult: 2.6, reliability: 0.998, goods: { composites: 1 }, tech: 'graphene_structures', description: 'Ultralight megastructure-grade material.' },
];

export const COMPONENTS: ComponentDef[] = [
  // ------------------------------------------------------------ Propulsion
  { id: 'eng_methalox', name: 'Methalox Engine', category: 'propulsion', description: 'A full-flow staged-combustion engine with high thrust and moderate efficiency. It can land and lift off from moons and Mars.', mass: 1.6, cost: 1.5e7, reliability: 0.998, complexity: 3, goods: { alloys: 1.2, machinery: 0.3, electronics: 0.02 }, thrust: 2300, isp: 375, propellant: 'propellant' },
  { id: 'eng_hydrolox', name: 'Hydrolox Vacuum Engine', category: 'propulsion', description: 'A high-efficiency cryogenic engine with lower thrust per engine.', mass: 2.0, cost: 2.0e7, reliability: 0.998, complexity: 3, goods: { alloys: 1.4, machinery: 0.4, electronics: 0.03 }, thrust: 500, isp: 455, propellant: 'propellant' },
  { id: 'eng_hall', name: 'Hall-Effect Thruster Cluster', category: 'propulsion', description: 'A 1-MW electric thruster cluster. Very efficient, very low thrust, and it needs power.', mass: 1.2, cost: 1.2e7, reliability: 0.999, complexity: 2, goods: { machinery: 0.5, electronics: 0.1, alloys: 0.4 }, thrust: 0.05, isp: 2200, propellant: 'argon', powerReq: 1.0, heat: 0.35 },
  { id: 'eng_vasimr', name: 'Magnetoplasma Thruster', category: 'propulsion', description: 'A 5-MW variable-impulse plasma rocket.', tech: 'advanced_electric_propulsion', mass: 5, cost: 6.0e7, reliability: 0.998, complexity: 4, goods: { machinery: 2, electronics: 0.4, superconductors: 0.05, alloys: 2 }, thrust: 0.15, isp: 5000, propellant: 'argon', powerReq: 5, heat: 2 },
  { id: 'eng_ntr', name: 'Nuclear Thermal Rocket', category: 'propulsion', description: 'A solid-core reactor that heats hydrogen. It doubles chemical efficiency while keeping useful thrust.', tech: 'nuclear_thermal_propulsion', mass: 9, cost: 3.0e8, reliability: 0.996, complexity: 6, goods: { alloys: 4, ceramics: 2, reactorFuel: 0.2, machinery: 1, electronics: 0.1 }, thrust: 330, isp: 900, propellant: 'hydrogen', heat: 3 },
  { id: 'eng_bimodal', name: 'Bimodal Nuclear Thermal Rocket', category: 'propulsion', description: 'An NTR that also generates 1 MW of electricity between burns.', tech: 'bimodal_ntr', mass: 11, cost: 4.0e8, reliability: 0.997, complexity: 7, goods: { alloys: 5, ceramics: 2.5, reactorFuel: 0.25, machinery: 1.2, electronics: 0.15 }, thrust: 300, isp: 950, propellant: 'hydrogen', powerGen: 1, heat: 4 },
  { id: 'eng_nep', name: 'Nuclear-Electric Ion Drive', category: 'propulsion', description: 'A 20-MW gridded-ion and Hall thruster bank. It needs a large reactor and radiators.', tech: 'nuclear_electric_propulsion', mass: 12, cost: 4.0e8, reliability: 0.998, complexity: 6, goods: { machinery: 4, electronics: 1, alloys: 5, superconductors: 0.1 }, thrust: 0.4, isp: 7000, propellant: 'argon', powerReq: 20, heat: 6 },
  { id: 'eng_fusion', name: 'Fusion Torch Drive', category: 'propulsion', description: 'A direct-fusion drive that exhausts plasma at 245 km/s. It turns months into weeks.', tech: 'fusion_drives', mass: 120, cost: 5.0e9, reliability: 0.996, complexity: 12, goods: { superconductors: 8, alloys: 60, machinery: 20, electronics: 3, ceramics: 20 }, thrust: 60, isp: 25000, propellant: 'hydrogen', powerGen: 20, heat: 60, fusionFuelRate: 0.0004 },
  { id: 'eng_fusion_adv', name: 'Aneutronic Torch Drive', category: 'propulsion', description: 'A p-B11 or D–He3 torch with 800 km/s exhaust.', tech: 'advanced_fusion_drives', mass: 200, cost: 2.0e10, reliability: 0.997, complexity: 16, goods: { superconductors: 15, alloys: 100, machinery: 30, electronics: 6, ceramics: 30 }, thrust: 200, isp: 80000, propellant: 'hydrogen', powerGen: 80, heat: 150, fusionFuelRate: 0.0025 },
  { id: 'eng_msail', name: 'Magnetic Sail', category: 'propulsion', description: 'A superconducting loop that deflects the solar wind. It needs no propellant and gives tiny thrust.', tech: 'magnetic_sails', mass: 15, cost: 8.0e8, reliability: 0.998, complexity: 6, goods: { superconductors: 3, alloys: 5, electronics: 0.5 }, thrust: 0.05, isp: 1e7, propellant: 'argon', powerReq: 0.5 },
  { id: 'eng_lasersail', name: 'Beam-Riding Laser Sail', category: 'propulsion', description: 'A reflective sail pushed by Helios power beams. It needs a working beam network.', tech: 'laser_sails', mass: 20, cost: 1.0e9, reliability: 0.998, complexity: 6, goods: { composites: 10, alloys: 5, electronics: 1 }, thrust: 0.5, isp: 1e7, propellant: 'argon', beamSail: true },
  // -------------------------------------------------------------- Tanks
  { id: 'tank_small', name: 'Propellant Tank (50 t)', category: 'tank', description: 'An insulated tank for methalox or hydrolox.', mass: 2.5, cost: 1.0e6, reliability: 0.9995, complexity: 1, goods: { alloys: 2, composites: 0.3 }, tankCapacity: 50, tankType: 'propellant' },
  { id: 'tank_large', name: 'Heavy Propellant Tank (500 t)', category: 'tank', description: 'A large cryogenic main tank.', mass: 20, cost: 6.0e6, reliability: 0.9995, complexity: 1, goods: { alloys: 17, composites: 2 }, tankCapacity: 500, tankType: 'propellant' },
  { id: 'tank_tanker', name: 'Tanker Section (2,000 t)', category: 'tank', description: 'A bulk propellant section for tankers and depot shuttles.', tech: 'cryogenic_depots', mass: 70, cost: 2.0e7, reliability: 0.9995, complexity: 2, goods: { alloys: 60, composites: 6 }, tankCapacity: 2000, tankType: 'propellant' },
  { id: 'tank_hydrogen', name: 'Liquid Hydrogen Tank (60 t)', category: 'tank', description: 'A bulky, heavily insulated tank for low-density LH₂.', mass: 7, cost: 5.0e6, reliability: 0.9995, complexity: 2, goods: { alloys: 5, composites: 1.5 }, tankCapacity: 60, tankType: 'hydrogen' },
  { id: 'tank_hydrogen_large', name: 'Hydrogen Tank Farm (600 t)', category: 'tank', description: 'A zero-boil-off LH₂ tankage section.', tech: 'nuclear_thermal_propulsion', mass: 55, cost: 4.0e7, reliability: 0.9995, complexity: 3, goods: { alloys: 40, composites: 12 }, tankCapacity: 600, tankType: 'hydrogen' },
  { id: 'tank_argon', name: 'Argon Tank (40 t)', category: 'tank', description: 'A high-pressure noble-gas storage tank.', mass: 1.5, cost: 1.0e6, reliability: 0.9998, complexity: 1, goods: { alloys: 1, composites: 0.4 }, tankCapacity: 40, tankType: 'argon' },
  { id: 'tank_argon_large', name: 'Argon Tank (400 t)', category: 'tank', description: 'A large argon storage section.', mass: 12, cost: 6.0e6, reliability: 0.9998, complexity: 1, goods: { alloys: 9, composites: 2.5 }, tankCapacity: 400, tankType: 'argon' },
  // -------------------------------------------------------------- Power
  { id: 'pwr_battery', name: 'Battery Pack', category: 'power', description: 'Short-term storage for small craft.', mass: 0.5, cost: 1.0e6, reliability: 0.999, complexity: 1, goods: { lithium: 0.2, electronics: 0.02, alloys: 0.2 }, powerGen: 0.05 },
  { id: 'pwr_solar', name: 'Solar Wing (0.5 MW)', category: 'power', description: 'Photovoltaic wing rated at 1 AU. Its output falls with the square of distance from the Sun.', mass: 3, cost: 5.0e6, reliability: 0.999, complexity: 1, goods: { photovoltaics: 2, alloys: 0.8, electronics: 0.05 }, powerGen: 0.5, solar: true },
  { id: 'pwr_solar_large', name: 'Roll-Out Solar Array (5 MW)', category: 'power', description: 'A large flexible-blanket array for solar-electric tugs.', tech: 'space_photovoltaics', mass: 18, cost: 3.0e7, reliability: 0.999, complexity: 2, goods: { photovoltaics: 10, alloys: 6, electronics: 0.3 }, powerGen: 5, solar: true },
  { id: 'pwr_fission', name: 'Kilopower Reactor (1 MW)', category: 'power', description: 'A compact fission reactor with a Stirling converter. It produces 3 MW of waste heat.', tech: 'surface_fission', mass: 6, cost: 1.0e8, reliability: 0.998, complexity: 4, goods: { alloys: 2, reactorFuel: 0.1, machinery: 1, ceramics: 1 }, powerGen: 1, heat: 3 },
  { id: 'pwr_fission_large', name: 'Space Fission Reactor (25 MW)', category: 'power', description: 'A Brayton-cycle reactor for nuclear-electric ships. It rejects 75 MW of heat.', tech: 'nuclear_electric_propulsion', mass: 45, cost: 1.2e9, reliability: 0.997, complexity: 8, goods: { alloys: 18, reactorFuel: 1, machinery: 8, ceramics: 6, electronics: 1 }, powerGen: 25, heat: 75 },
  { id: 'pwr_fusion', name: 'Fusion Reactor (500 MW)', category: 'power', description: 'A shipboard fusion core that rejects 1 GW of heat.', tech: 'fusion_power', mass: 250, cost: 1.5e10, reliability: 0.996, complexity: 14, goods: { superconductors: 15, alloys: 120, machinery: 40, ceramics: 40, electronics: 5 }, powerGen: 500, heat: 1000 },
  // -------------------------------------------------------------- Thermal
  { id: 'rad_panel', name: 'Radiator Panel (1 MW)', category: 'thermal', description: 'A pumped-loop radiator panel.', mass: 1.2, cost: 2.0e6, reliability: 0.999, complexity: 1, goods: { alloys: 0.8, copper: 0.2 }, radiator: 1 },
  { id: 'rad_heatpipe', name: 'Heat-Pipe Radiator (10 MW)', category: 'thermal', description: 'A high-temperature heat-pipe radiator array.', tech: 'advanced_thermal_control', mass: 8, cost: 2.0e7, reliability: 0.999, complexity: 2, goods: { alloys: 4, ceramics: 3, copper: 0.5 }, radiator: 10 },
  { id: 'rad_droplet', name: 'Liquid Droplet Radiator (100 MW)', category: 'thermal', description: 'Sprays sheets of hot droplets through space and recaptures them. It has the best rejection per unit mass.', tech: 'liquid_droplet_radiators', mass: 30, cost: 2.0e8, reliability: 0.998, complexity: 4, goods: { alloys: 15, ceramics: 8, machinery: 3 }, radiator: 100 },
  // ---------------------------------------------------------- Habitation
  { id: 'hab_capsule', name: 'Crew Capsule (4)', category: 'habitation', description: 'A short-duration capsule for four crew.', mass: 9, cost: 8.0e7, reliability: 0.999, complexity: 3, goods: { alloys: 5, composites: 1, electronics: 0.3, machinery: 0.5 }, crew: 4, enduranceDays: 60, powerReq: 0.02, heat: 0.02 },
  { id: 'hab_module', name: 'Transit Habitat (12)', category: 'habitation', description: 'A long-duration habitat with a storm shelter for twelve.', mass: 28, cost: 2.5e8, reliability: 0.999, complexity: 4, goods: { alloys: 15, composites: 5, electronics: 1, machinery: 2 }, crew: 12, enduranceDays: 500, powerReq: 0.06, heat: 0.06, shielding: 0.4 },
  { id: 'hab_passenger', name: 'Passenger Module (80)', category: 'habitation', description: 'A high-density passenger cabin for short transfers.', mass: 70, cost: 5.0e8, reliability: 0.999, complexity: 4, goods: { alloys: 40, composites: 12, electronics: 2, machinery: 3 }, crew: 80, enduranceDays: 200, powerReq: 0.2, heat: 0.2, shielding: 0.3 },
  { id: 'hab_spin', name: 'Spin-Gravity Ring (40)', category: 'habitation', description: 'A rotating ring that keeps crews healthy on multi-year voyages.', tech: 'rotating_habitats', mass: 160, cost: 2.0e9, reliability: 0.998, complexity: 8, goods: { alloys: 100, composites: 20, electronics: 4, machinery: 10 }, crew: 40, enduranceDays: 1200, powerReq: 0.4, heat: 0.4, spinGravity: true, shielding: 0.6 },
  { id: 'hab_colony', name: 'Colonist Transport Module (400)', category: 'habitation', description: 'A mass-migration module with a shielded core for four hundred settlers.', tech: 'large_pressure_structures', mass: 350, cost: 3.0e9, reliability: 0.998, complexity: 8, goods: { alloys: 200, composites: 40, electronics: 6, machinery: 15, water: 50 }, crew: 400, enduranceDays: 300, powerReq: 1.2, heat: 1.2, shielding: 0.6 },
  { id: 'shield_water', name: 'Water-Wall Storm Shelter', category: 'shielding', description: 'Water bladders around the crew quarters that block solar particle events.', mass: 15, cost: 1.0e7, reliability: 0.9999, complexity: 1, goods: { water: 12, composites: 2 }, shielding: 0.5 },
  // --------------------------------------------------------------- Cargo
  { id: 'cargo_bay', name: 'Cargo Bay (40 t)', category: 'cargo', description: 'A pressurized and unpressurized cargo carrier.', mass: 2.5, cost: 2.0e6, reliability: 0.9999, complexity: 1, goods: { alloys: 2, composites: 0.2 }, cargo: 40 },
  { id: 'cargo_large', name: 'Cargo Hold (400 t)', category: 'cargo', description: 'A modular container hold.', mass: 18, cost: 1.2e7, reliability: 0.9999, complexity: 1, goods: { alloys: 16, composites: 1 }, cargo: 400 },
  { id: 'cargo_bulk', name: 'Bulk Freight Frame (4,000 t)', category: 'cargo', description: 'An open truss for bulk ore, water and slag.', tech: 'orbital_assembly', mass: 110, cost: 6.0e7, reliability: 0.9999, complexity: 2, goods: { alloys: 100, composites: 4 }, cargo: 4000 },
  { id: 'cargo_mega', name: 'Megafreight Truss (40,000 t)', category: 'cargo', description: 'A nanotube freight spine for interplanetary bulk trade.', tech: 'graphene_structures', mass: 700, cost: 4.0e8, reliability: 0.9999, complexity: 3, goods: { composites: 600, alloys: 60 }, cargo: 40000 },
  // ----------------------------------------------------------- Navigation
  { id: 'nav_basic', name: 'Avionics Suite', category: 'navigation', description: 'Guidance, navigation and control for crewed flight.', mass: 0.3, cost: 5.0e6, reliability: 0.999, complexity: 2, goods: { electronics: 0.1, alloys: 0.1 }, navLevel: 1 },
  { id: 'nav_auto', name: 'Autonomous Flight System', category: 'navigation', description: 'Autonomous rendezvous, docking and landing. It allows uncrewed cargo operations.', mass: 0.4, cost: 1.5e7, reliability: 0.999, complexity: 2, goods: { electronics: 0.15, alloys: 0.1 }, navLevel: 2 },
  { id: 'nav_ai', name: 'AI Navigation Core', category: 'navigation', description: 'Predictive fault management and trajectory optimization. It raises mission reliability.', tech: 'ai_logistics', mass: 0.5, cost: 5.0e7, reliability: 0.9995, complexity: 3, goods: { electronics: 0.25, alloys: 0.1 }, navLevel: 3 },
  // -------------------------------------------------------- Communication
  { id: 'comm_radio', name: 'S-Band Radio', category: 'communication', description: 'Cislunar communications.', mass: 0.1, cost: 1.0e6, reliability: 0.9995, complexity: 1, goods: { electronics: 0.05 }, commRange: 'cislunar' },
  { id: 'comm_dish', name: 'High-Gain Microwave Dish', category: 'communication', description: 'Deep-space radio for interplanetary flight.', mass: 0.5, cost: 1.0e7, reliability: 0.9995, complexity: 1, goods: { electronics: 0.1, alloys: 0.3 }, commRange: 'interplanetary' },
  { id: 'comm_laser', name: 'Optical Laser Terminal', category: 'communication', description: 'High-bandwidth optical communications with better telemetry and fault recovery.', tech: 'laser_communications', mass: 0.2, cost: 2.0e7, reliability: 0.9998, complexity: 2, goods: { electronics: 0.1 }, commRange: 'interplanetary' },
  // ------------------------------------------------------------- Docking
  { id: 'dock_port', name: 'Docking Port', category: 'docking', description: 'A standard androgynous docking mechanism.', mass: 0.4, cost: 2.0e6, reliability: 0.9995, complexity: 1, goods: { alloys: 0.3, machinery: 0.05 }, docking: true },
  { id: 'dock_transfer', name: 'Robotic Cargo Transfer System', category: 'docking', description: 'Robotic arms and propellant couplings that halve port turnaround time.', mass: 3, cost: 2.0e7, reliability: 0.999, complexity: 3, goods: { machinery: 1.5, electronics: 0.1, alloys: 1 }, transferSpeed: 0.5 },
  // ------------------------------------------------------------------ Aero
  { id: 'aeroshell', name: 'Heat Shield & Aeroshell', category: 'aero', description: 'Allows aerobraking and atmospheric entry. Each unit protects about 300 t of entry mass.', mass: 12, cost: 3.0e7, reliability: 0.998, complexity: 2, goods: { ceramics: 8, composites: 3 }, aeroshell: true },
  // -------------------------------------------------------- Weapons/sensors
  { id: 'wpn_missile', name: 'Missile Bus', category: 'weapon', description: 'Long-range guided interceptors. They trade propellant for reach.', mass: 6, cost: 1.0e8, reliability: 0.998, complexity: 4, goods: { alloys: 3, electronics: 0.5, propellant: 2 }, combat: 8 },
  { id: 'wpn_railgun', name: 'Kinetic Railgun', category: 'weapon', description: 'An electromagnetic accelerator firing hypervelocity slugs.', tech: 'kinetic_interceptors', mass: 15, cost: 3.0e8, reliability: 0.997, complexity: 5, goods: { alloys: 8, copper: 2, electronics: 0.5, machinery: 2 }, combat: 15, powerReq: 5, heat: 1.5 },
  { id: 'wpn_laser', name: 'Free-Electron Laser', category: 'weapon', description: 'A megawatt-class directed-energy weapon. It needs large power and radiators.', tech: 'directed_energy', mass: 25, cost: 1.0e9, reliability: 0.996, complexity: 8, goods: { alloys: 10, electronics: 2, superconductors: 1, machinery: 3 }, combat: 30, powerReq: 20, heat: 12 },
  { id: 'wpn_pd', name: 'Point Defense Cluster', category: 'weapon', description: 'Close-in defense against missiles and debris.', tech: 'point_defense', mass: 4, cost: 8.0e7, reliability: 0.998, complexity: 3, goods: { alloys: 2, electronics: 0.3, machinery: 0.5 }, defense: 10, powerReq: 1, heat: 0.3 },
  { id: 'sensor_ir', name: 'Infrared Sensor Array', category: 'sensor', description: 'Passive detection of engine plumes and waste heat.', mass: 1, cost: 2.0e7, reliability: 0.999, complexity: 2, goods: { electronics: 0.2, alloys: 0.3 }, sensor: 10 },
  { id: 'sensor_adv', name: 'Deep-Space Sensor Suite', category: 'sensor', description: 'Multispectral telescopes, lidar and radar.', tech: 'advanced_sensors', mass: 4, cost: 1.5e8, reliability: 0.999, complexity: 4, goods: { electronics: 0.8, alloys: 1 }, sensor: 30 },
];

export const COMPONENT: Record<string, ComponentDef> = Object.fromEntries(COMPONENTS.map((c) => [c.id, c]));
export const STRUCTURE: Record<string, StructureDef> = Object.fromEntries(STRUCTURES.map((s) => [s.id, s]));
