import type { LawDef } from '../types';

// Axes: [federal, expansion, market, enhancement, machine, security, autonomy]
export const LAWS: LawDef[] = [
  // ------------------------------------------------------------------ Fiscal
  {
    id: 'assessment_increase', name: 'Assessment Adjustment Act', category: 'fiscal',
    description: 'Raises member-state assessments from 0.04% to 0.06% of GDP to fund common programs.',
    effectsText: ['Assessment rate +0.02% of member GDP', 'Member-state support falls'],
    nationsThreshold: 'super', assemblyThreshold: 'simple', axes: [0.6, 0.3, -0.2, 0, 0, 0, -0.1],
    interests: { earth: -0.6, developing: -0.3 }, modifiers: { assessmentRate: 0.0002 }, capitalCost: 30, repealable: true,
  },
  {
    id: 'orbital_licensing', name: 'Orbital Licensing Reform', category: 'fiscal',
    description: 'Doubles licensing fees on satellite constellations and orbital slots.',
    effectsText: ['Orbital licensing revenue ×2', 'Launch costs +2%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, -0.1, -0.3, 0, 0, 0.1, 0],
    interests: { corporate: -0.4, spacefaring: -0.2 }, modifiers: { licensingMult: 1, launchCost: 0.02 }, capitalCost: 15, repealable: true,
  },
  {
    id: 'resource_royalties', name: 'Space Resource Royalty Act', category: 'fiscal',
    description: 'Levies a 5% royalty on the value of all resources extracted beyond Earth.',
    effectsText: ['Royalty of 5% on extraction value', 'Corporate investment appetite −5%'],
    requires: { competency: ['resourcePolicy', 'shared'] },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, -0.1, -0.4, 0, 0, 0, -0.2],
    interests: { corporate: -0.5, offworld: -0.2, developing: 0.3 }, modifiers: { royaltyRate: 0.05, corpInvestment: -0.05 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'commercial_levy', name: 'Interplanetary Commerce Levy', category: 'fiscal',
    description: 'A 1.5% levy on the value of interplanetary trade, administered by the ICC.',
    effectsText: ['1.5% levy on off-world trade value'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, 0, -0.3, 0, 0, 0, -0.3],
    interests: { corporate: -0.3, offworld: -0.4 }, modifiers: { commercialLevy: 0.015 }, capitalCost: 15, repealable: true,
  },
  {
    id: 'corporate_tax', name: 'Federal Corporate Tax', category: 'fiscal',
    description: 'A 12% federal tax on the profits of corporations operating beyond Earth.',
    effectsText: ['12% tax on corporate space profits', 'Corporate investment appetite −10%'],
    requires: { competency: ['directTaxation', 'shared'] },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.5, -0.1, -0.7, 0, 0, 0, -0.1],
    interests: { corporate: -0.8, labor: 0.3 }, modifiers: { corporateTax: 0.12, corpInvestment: -0.1 }, capitalCost: 30, repealable: true,
  },
  {
    id: 'direct_tax', name: 'Common Contribution Act', category: 'fiscal',
    description: 'The first direct federal tax on citizens: 0.4% of income, collected by the UNE. It is a politically transformative step.',
    effectsText: ['Direct federal income tax (~0.2% of GDP)', 'Sovereigntist backlash'],
    requires: { competency: ['directTaxation', 'exclusive'] },
    nationsThreshold: 'super', assemblyThreshold: 'absolute', axes: [0.9, 0.2, -0.4, 0, 0, 0, -0.3],
    interests: { earth: -0.7, developing: -0.2 }, modifiers: { directTax: 0.002 }, capitalCost: 60, repealable: true,
  },
  {
    id: 'energy_tax', name: 'Solar Energy Levy', category: 'fiscal',
    description: 'A 5% levy on energy sold from the Helios swarm and orbital power stations.',
    effectsText: ['5% levy on beamed energy revenues'],
    requires: { competency: ['energyInfrastructure', 'shared'], tech: 'beamed_power' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, 0, -0.4, 0, 0, 0, -0.2],
    interests: { corporate: -0.4 }, modifiers: { energyTax: 0.05 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'bond_authority', name: 'Federal Borrowing Authority Act', category: 'fiscal',
    description: 'Authorizes the UNE to issue bonds up to three times its annual revenue for infrastructure.',
    effectsText: ['UNE may issue federal bonds', 'Debt ceiling: 3× annual revenue'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.5, 0.3, 0.1, 0, 0, 0, 0],
    interests: { earth: -0.1 }, modifiers: { debtCeiling: 2 }, capitalCost: 20, repealable: true,
  },
  // ------------------------------------------------------- Industry & settlement
  {
    id: 'lunar_fund', name: 'Lunar Industrialization Fund', category: 'industry',
    description: 'The UNE matches 30% of member-state and corporate investment in lunar facilities.',
    effectsText: ['UNE pays 30% of private and national lunar capex', 'Lunar investment +40%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, 0.7, 0.2, 0, 0.1, 0, 0],
    interests: { corporate: 0.6, spacefaring: 0.5, developing: -0.1 }, modifiers: { lunarFund: 0.3 }, capitalCost: 20, annualCost: 0, repealable: true,
  },
  {
    id: 'open_settlements', name: 'Open Settlements Act', category: 'industry',
    description: 'Allows corporations and member states to build facilities in UNE settlements without case-by-case approval.',
    effectsText: ['Private and national investment in UNE settlements +60%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [-0.1, 0.5, 0.6, 0, 0.1, 0, 0.1],
    interests: { corporate: 0.6, spacefaring: 0.4, labor: -0.1 }, modifiers: { openSettlements: 0.6 }, capitalCost: 15, repealable: true,
  },
  {
    id: 'corporate_charters', name: 'Corporate Settlement Charters', category: 'industry',
    description: 'Corporations may found and administer registered settlements at unclaimed sites.',
    effectsText: ['Corporations may found settlements', 'Corporate influence grows'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [-0.3, 0.6, 0.8, 0, 0.2, 0, 0.2],
    interests: { corporate: 0.9, labor: -0.3 }, modifiers: { corpCharters: 1 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'national_settlements', name: 'National Settlement Registration', category: 'industry',
    description: 'Member states may register national settlements under UNE law, which remains supreme.',
    effectsText: ['Member states may found settlements'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [-0.5, 0.6, 0.1, 0, 0, 0.1, 0],
    interests: { spacefaring: 0.8, earth: 0.3, developing: -0.2 }, modifiers: { nationalSettlements: 1 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'common_heritage', name: 'Common Heritage Resource Regime', category: 'industry', group: 'resource_regime',
    description: 'Strategic volatiles and deposits are managed as common infrastructure. Extraction licenses carry high royalties.',
    effectsText: ['Royalties +5% on extraction', 'Corporate investment −15%', 'Developing-state support rises'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.6, -0.2, -0.7, 0, 0, 0, -0.2],
    interests: { corporate: -0.8, developing: 0.7, spacefaring: -0.3 }, modifiers: { royaltyRate: 0.05, corpInvestment: -0.15 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'property_rights', name: 'Extraction Property Rights Act', category: 'industry', group: 'resource_regime',
    description: 'Actors own the resources they extract, and claims over worked deposits are recognized.',
    effectsText: ['Corporate investment +25%', 'Inequality and developing-state resentment rise'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [-0.4, 0.5, 0.9, 0, 0.1, 0, 0.1],
    interests: { corporate: 0.9, developing: -0.6, spacefaring: 0.4 }, modifiers: { corpInvestment: 0.25 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'mars_program', name: 'Mars Settlement Program', category: 'settlement',
    description: 'A multi-decade UNE program to establish humanity on Mars. It commits the SDA to martian logistics.',
    effectsText: ['Mars settlement costs −20%', 'Expansionist support rises', 'Requires Mars-capable propulsion'],
    requires: { tech: 'nuclear_thermal_propulsion' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, 0.9, 0, 0.1, 0.1, 0, 0],
    interests: { spacefaring: 0.5, developing: -0.2 }, modifiers: { marsDiscount: 0.2 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'automation_transition', name: 'Automation Transition Act', category: 'industry',
    description: 'Retraining, income support and profit-sharing for workers displaced by automation.',
    effectsText: ['Automation unrest −60%', 'Costs 0.02% of GDP (paid by member states)'],
    requires: { tech: 'industrial_ai' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, 0, -0.7, 0, -0.2, 0, 0],
    interests: { labor: 0.9, corporate: -0.3 }, modifiers: { automationUnrest: -0.6 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'replication_ban', name: 'Self-Replication Moratorium', category: 'industry', group: 'replication',
    description: 'Bans self-replicating industrial systems pending safety research.',
    effectsText: ['Self-replicating factories may not reproduce', 'AI and industrial risk −'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.2, -0.6, -0.2, -0.3, -0.7, 0.3, 0],
    interests: { corporate: -0.5, labor: 0.3 }, modifiers: { replication: -1, aiRisk: -0.05 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'replication_open', name: 'Open Replication Act', category: 'industry', group: 'replication',
    description: 'Licensed self-replicating industry may expand without per-copy approval, subject only to resource caps.',
    effectsText: ['Replication rate doubled', 'Replication incident risk rises'],
    requires: { tech: 'partial_self_replication' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0, 0.8, 0.4, 0.2, 0.8, -0.2, 0.1],
    interests: { corporate: 0.7, labor: -0.4 }, modifiers: { replication: 1, aiRisk: 0.05 }, capitalCost: 30, repealable: true,
  },
  // Mercury policy (§81–82)
  {
    id: 'mercury_preserve', name: 'Mercury Preservation Treaty', category: 'environment', group: 'mercury',
    description: 'Mercury is a scientific reserve. No industrial extraction is permitted.',
    effectsText: ['Mercury extraction cap: 0', 'Preservationist and scientific support rises'],
    requires: { condition: 'mercuryReached' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.2, -0.9, -0.3, 0, -0.2, 0, 0],
    interests: { corporate: -0.6 }, modifiers: { mercuryCap: -1 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'mercury_extensive', name: 'Mercury Industrial Charter', category: 'industry', group: 'mercury',
    description: 'Extensive surface mining of Mercury\'s crust, with protected scientific regions.',
    effectsText: ['Mercury extraction cap raised to 10¹³ t/yr', 'Creates the Mercury Industrial Authority'],
    requires: { condition: 'mercuryReached' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.2, 0.8, 0.3, 0, 0.3, 0, 0],
    interests: { corporate: 0.6 }, modifiers: { mercuryCap: 1 }, capitalCost: 30, repealable: true,
  },
  {
    id: 'mercury_disassembly', name: 'Mercury Disassembly Act', category: 'industry', group: 'mercury',
    description: 'Authorizes partial planetary disassembly, mining down into the mantle and iron core.',
    effectsText: ['Removes Mercury extraction caps (including the core)', 'Deep Preservationist opposition'],
    requires: { condition: 'mercuryIndustrial', tech: 'self_replicating_industry' },
    nationsThreshold: 'super', assemblyThreshold: 'absolute', axes: [0.2, 1, 0.3, 0.2, 0.6, 0, 0],
    interests: { corporate: 0.6, earth: -0.1 }, modifiers: { mercuryCap: 2 }, capitalCost: 50, repealable: true,
  },
  {
    id: 'energy_trust', name: 'Solar Energy Trust Act', category: 'energy', group: 'energy_regime',
    description: 'Half of all Helios swarm output is held in trust by the UNE for all citizens and funds a universal energy dividend.',
    effectsText: ['UNE receives 50% of swarm energy revenue', 'Corporate swarm investment −20%', 'Creates the Solar Energy Trust'],
    requires: { tech: 'dyson_collectors' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.7, 0.2, -0.8, 0, 0, 0, -0.2],
    interests: { corporate: -0.7, labor: 0.6, developing: 0.6 }, modifiers: { energyTrust: 0.5, corpInvestment: -0.05 }, capitalCost: 40, repealable: true,
  },
  {
    id: 'energy_market', name: 'Open Energy Market Act', category: 'energy', group: 'energy_regime',
    description: 'Swarm output is sold on open markets by collector owners.',
    effectsText: ['Corporate swarm investment +30%', 'Energy inequality rises'],
    requires: { tech: 'dyson_collectors' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [-0.3, 0.4, 0.9, 0, 0.1, 0, 0.2],
    interests: { corporate: 0.8, labor: -0.3 }, modifiers: { corpInvestment: 0.1, swarmCorp: 0.3 }, capitalCost: 25, repealable: true,
  },
  // ---------------------------------------------------------- Research & IP
  {
    id: 'research_commons', name: 'UNE Research Commons', category: 'research', group: 'ip',
    description: 'Member states pool a larger share of publicly funded research into an open UNE commons.',
    effectsText: ['National contributions to UNE research +60%', 'Corporate R&D −25%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.6, 0.2, -0.5, 0.1, 0.1, -0.2, 0],
    interests: { corporate: -0.4, developing: 0.5, spacefaring: -0.2 }, modifiers: { researchCommons: 0.6, corpRnD: -0.25 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'strong_patents', name: 'Interplanetary Patent Convention', category: 'research', group: 'ip',
    description: 'Strong, enforceable patents across all jurisdictions, including off-world.',
    effectsText: ['Corporate R&D +40%', 'UNE must license proprietary technologies'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [-0.2, 0.2, 0.8, 0.1, 0.2, 0, 0],
    interests: { corporate: 0.8, developing: -0.5 }, modifiers: { corpRnD: 0.4, researchCommons: -0.2 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'compulsory_licensing', name: 'Compulsory Licensing Act', category: 'research',
    description: 'The UNE may license any proprietary technology for common use in exchange for reasonable royalties.',
    effectsText: ['Proprietary technologies become usable by all actors', 'Corporate R&D −15%'],
    requires: { competency: ['corporateRegulation', 'shared'] },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.5, 0.2, -0.6, 0, 0, 0, 0],
    interests: { corporate: -0.8, developing: 0.5 }, modifiers: { compulsoryLicensing: 1, corpRnD: -0.15 }, capitalCost: 30, repealable: true,
  },
  // ------------------------------------------------- Citizenship & politics
  {
    id: 'une_citizenship', name: 'Common Citizenship Act', category: 'citizenship',
    description: 'Establishes UNE citizenship alongside national citizenship. It is automatic for anyone born beyond Earth.',
    effectsText: ['Off-world-born residents become UNE citizens', 'Colonial grievances −30%', 'Sovereigntists oppose'],
    requires: { competency: ['citizenship', 'shared'] },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.8, 0.3, 0, 0, 0, 0, 0.3],
    interests: { offworld: 0.8, earth: -0.3 }, modifiers: { citizenship: 1, colonialGrievance: -0.3 }, capitalCost: 30, repealable: true,
  },
  {
    id: 'offworld_representation', name: 'Off-World Representation Act', category: 'citizenship',
    description: 'Creates Assembly constituencies for settlements, apportioned by population.',
    effectsText: ['Off-world settlements elect Assembly members', 'Colonial grievances −40%'],
    requires: { condition: 'offworldPopulation' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.6, 0.3, 0, 0, 0, 0, 0.6],
    interests: { offworld: 0.9, earth: -0.2 }, modifiers: { offworldRepresentation: 1, colonialGrievance: -0.4 }, capitalCost: 30, repealable: true,
  },
  {
    id: 'self_government', name: 'Territorial Self-Government Framework', category: 'citizenship',
    description: 'A legal pathway for territories to gain elected legislatures and local budgets.',
    effectsText: ['Territories may advance to self-government more easily', 'Autonomy pressure −20%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0, 0.2, 0, 0, 0, -0.2, 0.7],
    interests: { offworld: 0.7 }, modifiers: { selfGovFramework: 1, colonialGrievance: -0.2 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'digital_democracy', name: 'Citizen Initiative Act', category: 'citizenship',
    description: 'Citizens may put legislation directly to referendum through secure deliberative platforms.',
    effectsText: ['Citizen support +5%', 'Polarization +', 'Institutional trust +'],
    requires: { tech: 'digital_democracy' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, 0, -0.1, 0, 0.2, -0.4, 0.3],
    interests: { earth: -0.2 }, modifiers: { citizenSupport: 0.05, polarization: 0.05, trust: 0.05 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'transparency', name: 'Federal Transparency Act', category: 'politics',
    description: 'Open budgets, audit powers, lobbying registers and whistleblower protection.',
    effectsText: ['Corruption −40%', 'Transparency +', 'Bureaucratic costs +5%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, 0, -0.2, 0, 0, -0.3, 0],
    interests: { corporate: -0.2 }, modifiers: { corruption: -0.4, transparency: 0.25, bureaucracyCost: 0.05 }, capitalCost: 15, repealable: true,
  },
  {
    id: 'lobbying_limits', name: 'Lobbying Limits Act', category: 'politics',
    description: 'Caps corporate political spending and bars the revolving door between agencies and firms.',
    effectsText: ['Corporate influence on votes −40%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, 0, -0.6, 0, 0, 0, 0],
    interests: { corporate: -0.8, labor: 0.4 }, modifiers: { corpInfluence: -0.4 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'algorithmic_administration', name: 'Algorithmic Administration Act', category: 'ai',
    description: 'AI systems run permitting, logistics planning and routine administration under human oversight.',
    effectsText: ['Bureaucratic effectiveness +20%', 'Human Preservation and Labor opposition'],
    requires: { tech: 'algorithmic_administration' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, 0.2, 0.1, 0.2, 0.9, 0, 0],
    interests: { labor: -0.5 }, modifiers: { bureaucracy: 0.2, aiRisk: 0.03 }, capitalCost: 25, repealable: true,
  },
  // ------------------------------------------------------------- Security
  {
    id: 'orbital_safety', name: 'Orbital Safety Standards', category: 'security',
    description: 'Mandatory deorbit, collision avoidance and debris bonds for everything in Earth orbit.',
    effectsText: ['Debris growth −40%', 'Launch costs +3%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, -0.1, -0.2, 0, 0, 0.2, 0],
    interests: { corporate: -0.2 }, modifiers: { debrisMitigation: 0.4, launchCost: 0.03 }, capitalCost: 10, repealable: true,
  },
  {
    id: 'pd_network', name: 'Planetary Defense Network Act', category: 'security',
    description: 'Funds a complete survey network and a standing deflection capability.',
    effectsText: ['Survey coverage grows +50% faster', 'PDC funding +3B cr/yr'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, 0.2, -0.1, 0, 0, 0.5, 0],
    interests: {}, modifiers: { surveyGrowth: 0.5, deflection: 0.05 }, capitalCost: 10, annualCost: 3e9, repealable: true,
  },
  {
    id: 'nuclear_deflection', name: 'Nuclear Deflection Authority', category: 'security',
    description: 'Authorizes the PDC to use nuclear explosive devices to deflect imminent impactors.',
    effectsText: ['Deflection success +25% for short-warning threats', 'Arms-control concerns'],
    nationsThreshold: 'super', assemblyThreshold: 'simple', axes: [0.4, 0, 0, 0, 0, 0.7, -0.1],
    interests: { earth: -0.1 }, modifiers: { deflection: 0.25, tension: 0.02 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'security_forces', name: 'UNE Security Forces Act', category: 'security',
    description: 'Creates a federal security service for counter-piracy, patrols and crisis response.',
    effectsText: ['Creates the UNE Security Forces', 'Piracy and sabotage suppressed'],
    requires: { competency: ['militaryCommand', 'limited'] },
    nationsThreshold: 'super', assemblyThreshold: 'simple', axes: [0.6, 0.1, -0.1, 0, 0, 0.8, -0.3],
    interests: { earth: -0.3, offworld: -0.1 }, modifiers: { securityForces: 1 }, capitalCost: 30, repealable: true,
  },
  {
    id: 'aws_ban', name: 'Autonomous Weapons Convention', category: 'security',
    description: 'Bans lethal autonomous weapons beyond Earth.',
    effectsText: ['AI risk −', 'Security Bloc opposition'],
    nationsThreshold: 'super', assemblyThreshold: 'simple', axes: [0.3, 0, 0, 0, -0.6, -0.4, 0],
    interests: {}, modifiers: { aiRisk: -0.08, tension: -0.02 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'arms_control', name: 'Outer Space Arms Control Treaty', category: 'security',
    description: 'Verifiable limits on orbital weapons and kinetic bombardment systems.',
    effectsText: ['International tension −', 'Strategic weapon risk −'],
    nationsThreshold: 'super', assemblyThreshold: 'simple', axes: [0.4, 0, 0, 0, 0, -0.6, 0],
    interests: { spacefaring: -0.2 }, modifiers: { tension: -0.05 }, capitalCost: 25, repealable: true,
  },
  // ---------------------------------------------------------- Environment & health
  {
    id: 'planetary_protection', name: 'Planetary Protection Act', category: 'environment',
    description: 'Strict contamination controls around potential biospheres at Europa, Enceladus and Mars special regions.',
    effectsText: ['No settlement at biosignature candidate sites', 'Scientific prestige +'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.2, -0.7, -0.2, 0, 0, 0, 0],
    interests: { corporate: -0.2 }, modifiers: { planetaryProtection: 1 }, capitalCost: 15, repealable: true,
  },
  {
    id: 'climate_compact', name: 'Earth Climate Compact', category: 'environment',
    description: 'Coordinated decarbonization and climate adaptation, financed partly through space-based solar power.',
    effectsText: ['Earth climate stress growth −50%', 'Member GDP growth −0.1%/yr during transition'],
    requires: { competency: ['environment', 'shared'] },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.5, -0.5, -0.4, 0, 0, 0, 0],
    interests: { earth: -0.2, developing: 0.2 }, modifiers: { climateMitigation: 0.5, gdpDrag: 0.001 }, capitalCost: 25, repealable: true,
  },
  {
    id: 'gravity_standards', name: 'Low-Gravity Health Standards', category: 'environment',
    description: 'Mandatory centrifuge time, pediatric monitoring and medical staffing in low-gravity settlements.',
    effectsText: ['Low-gravity health damage −30%', 'Settlement operating costs +5%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.3, -0.1, -0.3, 0, 0, 0, -0.1],
    interests: { offworld: 0.3, corporate: -0.2 }, modifiers: { gravityHealth: -0.3, settlementCost: 0.05 }, capitalCost: 10, repealable: true,
  },
  {
    id: 'enhancement_ban', name: 'Human Genome Integrity Act', category: 'genetics', group: 'enhancement',
    description: 'Bans heritable genetic enhancement.',
    effectsText: ['Radiation-resistance editing disabled', 'Human Preservation support rises'],
    requires: { tech: 'gene_therapy' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0, -0.2, 0, -0.95, -0.3, 0.1, 0],
    interests: { offworld: -0.4 }, modifiers: { enhancementBan: 1 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'enhancement_permitted', name: 'Adaptive Medicine Act', category: 'genetics', group: 'enhancement',
    description: 'Permits regulated heritable enhancements for radiation and low-gravity adaptation.',
    effectsText: ['Off-world health +', 'Transhumanist support rises', 'Opens the door to divergent human populations'],
    requires: { tech: 'human_adaptation' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0, 0.4, 0.2, 0.95, 0.3, 0, 0.3],
    interests: { offworld: 0.6 }, modifiers: { enhancementPermitted: 1 }, capitalCost: 30, repealable: true,
  },
  {
    id: 'ai_oversight', name: 'AI Oversight Act', category: 'ai',
    description: 'Creates the AI Oversight Board to license and audit advanced autonomous systems.',
    effectsText: ['AI risk −40%', 'Automation growth −10%', 'Creates the AI Oversight Board'],
    requires: { tech: 'industrial_ai' },
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, -0.1, -0.2, 0, -0.5, 0.2, 0],
    interests: { corporate: -0.3 }, modifiers: { aiOversight: 1, aiRiskMult: -0.4, automationGrowth: -0.1 }, capitalCost: 20, repealable: true,
  },
  {
    id: 'ai_personhood', name: 'Machine Personhood Act', category: 'ai',
    description: 'Grants limited legal personhood to artificial minds that meet cognitive criteria.',
    effectsText: ['Machine Integration support rises sharply', 'Human Preservation backlash', 'Research +10%'],
    requires: { tech: 'machine_cognition' },
    nationsThreshold: 'super', assemblyThreshold: 'absolute', axes: [0.2, 0.2, 0, 0.5, 1, -0.2, 0.2],
    interests: { labor: -0.4 }, modifiers: { researchMult: 0.1, aiRiskMult: -0.2 }, capitalCost: 40, repealable: true,
  },
  // --------------------------------------------------------------- Transport
  {
    id: 'freight_subsidy', name: 'Colonial Freight Subsidy', category: 'transport',
    description: 'The UNE pays 25% of freight costs on supply routes to settlements.',
    effectsText: ['UNE pays 25% of settlement freight costs', 'Colonial sentiment +'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, 0.5, -0.3, 0, 0, 0, 0.2],
    interests: { offworld: 0.6, earth: -0.2 }, modifiers: { freightSubsidy: 0.25 }, capitalCost: 15, repealable: true,
  },
  {
    id: 'nav_standards', name: 'Common Navigation Standards', category: 'transport',
    description: 'Unified navigation, docking and propellant-coupling standards across all fleets.',
    effectsText: ['Ship reliability +', 'Freight costs −3%'],
    nationsThreshold: 'qualified', assemblyThreshold: 'simple', axes: [0.4, 0.2, 0.1, 0, 0.1, 0, 0],
    interests: { corporate: 0.2 }, modifiers: { reliability: 0.001, freightCost: -0.03 }, capitalCost: 10, repealable: true,
  },
  // ------------------------------------------------------ Constitutional amendments
  {
    id: 'amd_taxation', name: 'Amendment I: Federal Taxation Powers', category: 'constitutional',
    description: 'Moves direct taxation from a limited to a shared competency, allowing federal corporate taxes.',
    effectsText: ['Direct taxation: Limited → Shared', 'Enables the Federal Corporate Tax'],
    amendment: { directTaxation: 'shared' }, requires: { notLaws: [] },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.8, 0.1, -0.3, 0, 0, 0, -0.2],
    interests: { earth: -0.5, corporate: -0.4 }, capitalCost: 50, repealable: false,
  },
  {
    id: 'amd_direct_tax', name: 'Amendment II: Common Treasury', category: 'constitutional',
    description: 'Makes direct taxation an exclusive UNE competency for its assigned bases, enabling a federal income tax.',
    effectsText: ['Direct taxation: Shared → Exclusive', 'Enables the Common Contribution Act'],
    amendment: { directTaxation: 'exclusive' }, requires: { laws: ['amd_taxation'] },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.95, 0.1, -0.3, 0, 0, 0, -0.3],
    interests: { earth: -0.8 }, capitalCost: 70, repealable: false,
  },
  {
    id: 'amd_citizenship', name: 'Amendment III: Common Citizenship', category: 'constitutional',
    description: 'Makes citizenship a shared competency, so the UNE can confer its own citizenship.',
    effectsText: ['Citizenship: National → Shared', 'Enables the Common Citizenship Act'],
    amendment: { citizenship: 'shared' },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.8, 0.2, 0, 0, 0, 0, 0.3],
    interests: { earth: -0.4, offworld: 0.7 }, capitalCost: 50, repealable: false,
  },
  {
    id: 'amd_security', name: 'Amendment IV: Federal Security', category: 'constitutional',
    description: 'Makes military command beyond Earth a shared competency.',
    effectsText: ['Military command: Limited → Shared', 'UNE security forces may grow without cap'],
    amendment: { militaryCommand: 'shared' },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.7, 0, 0, 0, 0, 0.8, -0.4],
    interests: { earth: -0.5 }, capitalCost: 50, repealable: false,
  },
  {
    id: 'amd_energy', name: 'Amendment V: Solar Energy Authority', category: 'constitutional',
    description: 'Makes interplanetary energy infrastructure an exclusive competency.',
    effectsText: ['Energy infrastructure: Shared → Exclusive', 'UNE regulates Helios output allocation'],
    amendment: { energyInfrastructure: 'exclusive' }, requires: { tech: 'beamed_power' },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.8, 0.2, -0.4, 0, 0, 0, -0.2],
    interests: { corporate: -0.6, earth: -0.2 }, capitalCost: 50, repealable: false,
  },
  {
    id: 'amd_migration', name: 'Amendment VI: Freedom of Movement', category: 'constitutional',
    description: 'Makes off-world migration exclusive, guaranteeing free movement between settlements.',
    effectsText: ['Off-world migration: Shared → Exclusive', 'Migration flows +30%'],
    amendment: { offworldMigration: 'exclusive' },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.6, 0.5, 0.2, 0, 0, -0.2, 0.2],
    interests: { offworld: 0.5, earth: -0.2 }, modifiers: { migration: 0.3 }, capitalCost: 40, repealable: false,
  },
  {
    id: 'amd_emergency', name: 'Amendment VII: Emergency Powers Framework', category: 'constitutional',
    description: 'Defines emergency powers, sunset clauses and court review. Emergencies become safer and more legitimate.',
    effectsText: ['Constitutional stability +', 'Emergency declarations cost less legitimacy'],
    amendment: {},
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.4, 0, 0, 0, 0, 0.3, 0],
    interests: {}, modifiers: { emergencyFramework: 1, stability: 0.05 }, capitalCost: 35, repealable: false,
  },
  {
    id: 'amd_direct_sg', name: 'Amendment VIII: Direct Election of the Secretary-General', category: 'constitutional',
    description: 'Citizens elect the Secretary-General directly.',
    effectsText: ['Secretary-General chosen by popular vote', 'Citizen support +', 'Executive legitimacy +'],
    amendment: {},
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.6, 0, 0, 0, 0, 0, 0.1],
    interests: { earth: -0.3 }, modifiers: { directSG: 1, citizenSupport: 0.03 }, capitalCost: 45, repealable: false,
  },
  {
    id: 'amd_devolution', name: 'Amendment IX: Confederal Devolution', category: 'constitutional',
    description: 'Returns several shared competencies to member states and colonies, loosening the union.',
    effectsText: ['Space industry, research and migration: Shared → Limited', 'State support +', 'Federal capacity −'],
    amendment: { spaceIndustry: 'limited', research: 'limited', offworldMigration: 'limited', corporateRegulation: 'limited' },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [-0.9, 0, 0.2, 0, 0, -0.3, 0.6],
    interests: { earth: 0.5, offworld: 0.4 }, modifiers: { stateSupport: 0.08 }, capitalCost: 40, repealable: false,
  },
  {
    id: 'amd_solar_compact', name: 'The Solar Compact', category: 'constitutional',
    description: 'Replaces the Earth Compact. It creates a People\'s Assembly of all citizens and a Council of Worlds of all polities, and renames the union.',
    effectsText: ['Constitutional refounding', 'Off-world polities gain equal standing', 'The UNE may be renamed'],
    amendment: { citizenship: 'exclusive', offworldMigration: 'exclusive' }, requires: { laws: ['offworld_representation'], offworldShare: 0.08 },
    nationsThreshold: 'super', assemblyThreshold: 'super', axes: [0.8, 0.4, 0, 0, 0, 0, 0.5],
    interests: { offworld: 1, earth: -0.4 }, modifiers: { solarCompact: 1 }, capitalCost: 80, repealable: false,
  },
];

export const LAW: Record<string, LawDef> = Object.fromEntries(LAWS.map((l) => [l.id, l]));
