import type { SiteDef, DepositDef } from '../types';

const regHighland = (reserve = 1e12, grade = 1): DepositDef => ({
  type: 'regolith', name: 'Highland regolith', reserve, grade, difficulty: 1,
  yields: { oxygen: 0.2, silicon: 0.1, aluminium: 0.07, iron: 0.03, titanium: 0.003 },
});
const regMare = (reserve = 1e12, grade = 1): DepositDef => ({
  type: 'regolith', name: 'Mare basalt regolith', reserve, grade, difficulty: 1,
  yields: { oxygen: 0.2, silicon: 0.09, iron: 0.1, titanium: 0.04, aluminium: 0.04 },
});
const lunarIce = (reserve: number, grade = 1): DepositDef => ({
  type: 'ice', name: 'Polar icy regolith', reserve, grade, difficulty: 1.4,
  yields: { water: 0.056, carbon: 0.001, nitrogen: 0.0005 },
});
const he3 = (reserve: number, grade = 1): DepositDef => ({
  type: 'he3', name: 'Solar-wind implanted helium-3', reserve, grade, difficulty: 2,
  yields: { fusionFuel: 1.5e-8, hydrogen: 5e-5, nitrogen: 1e-5 },
});
const marsAtmo = (grade = 1): DepositDef => ({
  type: 'atmosphere', name: 'CO₂ atmosphere', reserve: 2.5e13, grade, difficulty: 1,
  yields: { oxygen: 0.72, carbon: 0.26, nitrogen: 0.02, argon: 0.019 },
});
const marsRegolith = (grade = 1): DepositDef => ({
  type: 'regolith', name: 'Iron-rich martian regolith', reserve: 1e13, grade, difficulty: 1,
  yields: { oxygen: 0.2, silicon: 0.2, iron: 0.13, aluminium: 0.05, sulfur: 0.02, titanium: 0.005, water: 0.02 },
});
const marsIce = (reserve: number, grade = 1): DepositDef => ({
  type: 'ice', name: 'Buried water-ice sheet', reserve, grade, difficulty: 1,
  yields: { water: 0.6 },
});
const carbonaceous = (reserve: number, grade = 1): DepositDef => ({
  type: 'carbonaceous', name: 'Carbonaceous chondrite', reserve, grade, difficulty: 1.2,
  yields: { water: 0.08, carbon: 0.04, nitrogen: 0.002, phosphorus: 0.0005, iron: 0.15, nickel: 0.01, pgm: 1e-6 },
});
const metallic = (reserve: number, grade = 1): DepositDef => ({
  type: 'metal', name: 'Iron-nickel metal', reserve, grade, difficulty: 1.6,
  yields: { iron: 0.85, nickel: 0.09, copper: 0.002, pgm: 1.5e-5 },
});
const icyMoon = (reserve: number, water = 0.9, grade = 1): DepositDef => ({
  type: 'ice', name: 'Water-ice crust', reserve, grade, difficulty: 1.1,
  yields: { water, nitrogen: 0.005, carbon: 0.005 },
});

export const SITES: SiteDef[] = [
  // --- Earth orbit ---------------------------------------------------------
  { id: 'leo', name: 'Low Earth Orbit', body: 'earth', kind: 'orbital', region: 'earthOrbit', gravity: 0, radiation: 150, illumination: 0.62, deposits: [], features: ['earthGateway'], node: 'leo', description: 'The busiest place off Earth. Commercial stations, fuel depots and the terminus of every surface launch.' },
  { id: 'geo', name: 'Geostationary Orbit', body: 'earth', kind: 'orbital', region: 'earthOrbit', gravity: 0, radiation: 800, illumination: 0.99, deposits: [], features: ['comms'], node: 'geo', description: 'Home of the communications belt, and a candidate site for space-based solar power.' },
  { id: 'eml1', name: 'Earth–Moon L1', body: 'earth', kind: 'orbital', region: 'earthOrbit', gravity: 0, radiation: 600, illumination: 1, deposits: [], features: ['depot'], node: 'eml1', description: 'A balance point between Earth and the Moon, and the ideal crossroads for cislunar propellant depots.' },
  { id: 'eml5', name: 'Earth–Moon L5', body: 'earth', kind: 'orbital', region: 'earthOrbit', gravity: 0, radiation: 600, illumination: 1, deposits: [], features: ['habitatZone'], node: 'eml5', description: 'The stable Lagrange point O\'Neill proposed for giant rotating habitats built from lunar materials.' },
  // --- Luna ---------------------------------------------------------------
  { id: 'luna_gateway', name: 'Lunar Gateway (NRHO)', body: 'moon', kind: 'orbital', region: 'luna', gravity: 0, radiation: 600, illumination: 0.98, deposits: [], features: ['depot'], node: 'llo', description: 'A near-rectilinear halo orbit that offers continuous Earth contact and cheap access to the lunar poles.' },
  { id: 'luna_shackleton', name: 'Shackleton Rim', body: 'moon', kind: 'surface', region: 'luna', gravity: 0.165, radiation: 380, illumination: 0.85, deposits: [lunarIce(6e8, 1.1), regHighland()], features: ['polarIce', 'eternalLight'], node: 'luna_shackleton', description: 'Near-continuous sunlight on the crater rim above permanently shadowed, ice-bearing craters. It is the most contested real estate beyond Earth.' },
  { id: 'luna_malapert', name: 'Malapert Massif', body: 'moon', kind: 'surface', region: 'luna', gravity: 0.165, radiation: 380, illumination: 0.8, deposits: [lunarIce(2.5e8, 0.9), regHighland()], features: ['polarIce', 'earthView'], node: 'luna_malapert', description: 'A 5-km mountain near the south pole with a direct line of sight to Earth for communications.' },
  { id: 'luna_tranquillitatis', name: 'Mare Tranquillitatis', body: 'moon', kind: 'surface', region: 'luna', gravity: 0.165, radiation: 380, illumination: 0.5, deposits: [regMare(1e12, 1.1), he3(1e11, 1.2)], features: ['lavaTubes'], node: 'luna_tranquillitatis', description: 'Titanium-rich basalt plains with large lava-tube skylights, and the richest helium-3 regolith on the Moon.' },
  { id: 'luna_procellarum', name: 'Oceanus Procellarum', body: 'moon', kind: 'surface', region: 'luna', gravity: 0.165, radiation: 380, illumination: 0.5, deposits: [regMare(), he3(8e10), { type: 'kreep', name: 'KREEP basalts', reserve: 5e9, grade: 1, difficulty: 1.5, yields: { thorium: 1.5e-5, uranium: 4e-6, rareEarths: 5e-4, phosphorus: 5e-3 } }], features: ['lavaTubes', 'kreep'], node: 'luna_procellarum', description: 'The KREEP terrane is rich in thorium, rare-earth elements and phosphorus, the elements a closed lunar economy needs.' },
  { id: 'luna_daedalus', name: 'Daedalus Crater (Far Side)', body: 'moon', kind: 'surface', region: 'luna', gravity: 0.165, radiation: 380, illumination: 0.5, deposits: [regHighland(5e11)], features: ['radioQuiet'], node: 'luna_daedalus', description: 'The most radio-quiet place in the inner Solar System. It is an astronomer\'s sanctuary, shielded from Earth by 3,500 km of rock.' },
  // --- Near-Earth asteroids ----------------------------------------------
  { id: 'nea_bennu', name: '101955 Bennu', body: 'bennu', kind: 'asteroid', region: 'nea', gravity: 0.00001, radiation: 600, illumination: 0.95, deposits: [carbonaceous(7.3e7, 1)], features: ['hazardous'], node: 'nea_bennu', description: 'A carbonaceous rubble pile that also carries a small chance of striking Earth late next century.' },
  { id: 'nea_ryugu', name: '162173 Ryugu', body: 'ryugu', kind: 'asteroid', region: 'nea', gravity: 0.00001, radiation: 600, illumination: 0.95, deposits: [carbonaceous(4.5e8, 1.1)], features: [], node: 'nea_ryugu', description: 'A water- and organics-bearing asteroid that is energetically closer than the Moon\'s surface.' },
  { id: 'nea_amun', name: '3554 Amun', body: 'amun', kind: 'asteroid', region: 'nea', gravity: 0.0001, radiation: 600, illumination: 1.0, deposits: [metallic(3.5e10, 1)], features: [], node: 'nea_amun', description: 'A two-kilometre ball of iron, nickel, cobalt and platinum-group metals on a steeply inclined orbit.' },
  // --- Mars --------------------------------------------------------------
  { id: 'mars_orbit', name: 'Low Mars Orbit', body: 'mars', kind: 'orbital', region: 'mars', gravity: 0, radiation: 450, illumination: 0.62, deposits: [], features: ['depot'], node: 'lmo', description: 'The staging orbit for landings across Mars.' },
  { id: 'phobos', name: 'Phobos (Stickney)', body: 'phobos', kind: 'asteroid', region: 'mars', gravity: 0.0006, radiation: 400, illumination: 0.6, deposits: [{ type: 'carbonaceous', name: 'D-type regolith', reserve: 1e13, grade: 0.6, difficulty: 1.2, yields: { water: 0.02, carbon: 0.02, iron: 0.1, silicon: 0.15, oxygen: 0.3 } }], features: ['depot'], node: 'phobos', description: 'A shielding-rich moon in low Mars orbit, suited to a propellant depot and a staging port.' },
  { id: 'deimos', name: 'Deimos', body: 'deimos', kind: 'asteroid', region: 'mars', gravity: 0.0003, radiation: 400, illumination: 0.6, deposits: [{ type: 'carbonaceous', name: 'D-type regolith', reserve: 1.5e12, grade: 0.6, difficulty: 1.2, yields: { water: 0.02, carbon: 0.02, iron: 0.1, silicon: 0.15, oxygen: 0.3 } }], features: [], node: 'deimos', description: 'The outer moon of Mars, just 0.2 km/s from martian escape.' },
  { id: 'mars_jezero', name: 'Jezero Crater', body: 'mars', kind: 'surface', region: 'mars', gravity: 0.38, radiation: 230, illumination: 0.45, deposits: [marsAtmo(), marsRegolith(1.1), { type: 'minerals', name: 'Carbonates and clays', reserve: 2e9, grade: 1, difficulty: 1.3, yields: { carbon: 0.03, phosphorus: 0.003, lithium: 3e-5, copper: 4e-5, iron: 0.05 } }], features: ['river delta'], node: 'mars_jezero', description: 'An ancient river delta with carbonates, clays and a record of early martian habitability.' },
  { id: 'mars_arcadia', name: 'Arcadia Planitia', body: 'mars', kind: 'surface', region: 'mars', gravity: 0.38, radiation: 230, illumination: 0.42, deposits: [marsIce(1e11, 1.1), marsAtmo(), marsRegolith()], features: ['groundIce'], node: 'mars_arcadia', description: 'Flat northern plains with thick water-ice sheets metres below the surface. It is the best site for a large settlement.' },
  { id: 'mars_hellas', name: 'Hellas Basin', body: 'mars', kind: 'surface', region: 'mars', gravity: 0.38, radiation: 150, illumination: 0.42, deposits: [marsIce(3e10, 0.8), marsAtmo(1.1), marsRegolith()], features: ['thickAir'], node: 'mars_hellas', description: 'The deepest basin on Mars. Its air pressure exceeds the water triple point and cuts surface radiation by a third.' },
  { id: 'mars_arsia', name: 'Arsia Mons Caves', body: 'mars', kind: 'surface', region: 'mars', gravity: 0.38, radiation: 200, illumination: 0.5, deposits: [marsAtmo(0.6), marsRegolith(1.2)], features: ['lavaTubes', 'equatorial'], node: 'mars_arsia', description: 'Tharsis lava tubes near the equator. They offer natural radiation shelter and a high-altitude launch advantage.' },
  { id: 'mars_nili', name: 'Nili Fossae', body: 'mars', kind: 'surface', region: 'mars', gravity: 0.38, radiation: 230, illumination: 0.45, deposits: [marsAtmo(), marsRegolith(), { type: 'minerals', name: 'Olivine and sulfide terrain', reserve: 8e9, grade: 1.2, difficulty: 1.4, yields: { nickel: 0.002, copper: 1e-4, lithium: 6e-5, rareEarths: 3e-5, phosphorus: 0.004, iron: 0.08, sulfur: 0.01 } }], features: ['minerals'], node: 'mars_nili', description: 'Mineral-rich troughs with olivine, carbonates and hydrothermal sulfides, the metallurgical heart of a future Mars.' },
  // --- Venus -------------------------------------------------------------
  { id: 'venus_orbit', name: 'Low Venus Orbit', body: 'venus', kind: 'orbital', region: 'venus', gravity: 0, radiation: 500, illumination: 0.95, deposits: [], features: [], node: 'lvo', description: 'Orbit above the brilliant cloud deck, with 1.9 times Earth\'s sunlight.' },
  { id: 'venus_clouds', name: 'Aphrodite Cloud Level', body: 'venus', kind: 'atmospheric', region: 'venus', gravity: 0.9, radiation: 3, illumination: 1.1, deposits: [{ type: 'atmosphere', name: 'CO₂–N₂ atmosphere', reserve: 4.8e17, grade: 1, difficulty: 1, yields: { oxygen: 0.7, carbon: 0.26, nitrogen: 0.035, sulfur: 0.0015, water: 2e-5 } }], features: ['aerostat'], node: 'venus_clouds', description: 'At 52 km altitude the air is 1 bar and 25 °C, and breathable air is a lifting gas. The catch is a terrible gravity well to orbit.' },
  // --- Mercury -----------------------------------------------------------
  { id: 'mercury_orbit', name: 'Low Mercury Orbit', body: 'mercury', kind: 'orbital', region: 'mercury', gravity: 0, radiation: 1200, illumination: 0.9, deposits: [], features: ['swarmStaging'], node: 'lmeo', description: 'Orbit around the innermost planet, drenched in 9 kW of sunlight per square metre.' },
  { id: 'mercury_prokofiev', name: 'Prokofiev Crater (North Pole)', body: 'mercury', kind: 'surface', region: 'mercury', gravity: 0.38, radiation: 1000, illumination: 0.45, deposits: [icyMoon(4e10, 0.3, 1), { type: 'crust', name: 'Sulfur-rich silicate crust', reserve: 1e17, grade: 1, difficulty: 1.2, yields: { oxygen: 0.4, silicon: 0.25, aluminium: 0.06, iron: 0.04, sulfur: 0.03, titanium: 0.003 } }], features: ['polarIce'], node: 'mercury_prokofiev', description: 'A polar crater whose permanent shadows hold water ice, only kilometres from blazing sunlit plains.' },
  { id: 'mercury_caloris', name: 'Caloris Planitia', body: 'mercury', kind: 'surface', region: 'mercury', gravity: 0.38, radiation: 1000, illumination: 0.5, deposits: [{ type: 'crust', name: 'Sulfur-rich silicate crust', reserve: 1e18, grade: 1.1, difficulty: 1.2, yields: { oxygen: 0.4, silicon: 0.25, aluminium: 0.06, iron: 0.05, sulfur: 0.03, titanium: 0.003 } }, { type: 'core', name: 'Deep mantle and iron core (disassembly only)', reserve: 3.0e20, grade: 1, difficulty: 4, yields: { iron: 0.65, nickel: 0.06, silicon: 0.1, oxygen: 0.1, pgm: 1e-6 } }], features: ['equatorial', 'massDriverSite'], node: 'mercury_caloris', description: 'A 1,500-km impact basin on the equator, where mass drivers can fling cargo directly into solar orbit.' },
  // --- Main belt ---------------------------------------------------------
  { id: 'ceres_orbit', name: 'Ceres Orbit', body: 'ceres', kind: 'orbital', region: 'belt', gravity: 0, radiation: 450, illumination: 0.95, deposits: [], features: ['habitatZone', 'depot'], node: 'ceres_orbit', description: 'Orbital space around Ceres, where Belt habitats can draw on Cererian water and carbon.' },
  { id: 'ceres', name: 'Ceres (Occator)', body: 'ceres', kind: 'surface', region: 'belt', gravity: 0.029, radiation: 400, illumination: 0.5, deposits: [icyMoon(1e16, 0.22, 1), { type: 'carbonaceous', name: 'Ammoniated clays', reserve: 1e16, grade: 1.1, difficulty: 1.1, yields: { water: 0.1, carbon: 0.1, nitrogen: 0.01, phosphorus: 5e-4, iron: 0.1, nickel: 0.005 } }, { type: 'minerals', name: 'Occator brine salts', reserve: 5e10, grade: 1, difficulty: 1.2, yields: { lithium: 1e-4, carbon: 0.05, sulfur: 0.02, phosphorus: 1e-3 } }], features: ['brines'], node: 'ceres', description: 'A water world disguised as a dwarf planet, whose Occator faculae are bright brine deposits.' },
  { id: 'vesta', name: 'Vesta (Rheasilvia)', body: 'vesta', kind: 'surface', region: 'belt', gravity: 0.025, radiation: 400, illumination: 0.55, deposits: [{ type: 'regolith', name: 'Eucrite basalt', reserve: 1e15, grade: 1.1, difficulty: 1, yields: { oxygen: 0.4, silicon: 0.22, iron: 0.12, aluminium: 0.06, titanium: 0.005, nickel: 0.002 } }], features: [], node: 'vesta', description: 'A basaltic protoplanet whose excavated mantle is exposed in the vast Rheasilvia basin.' },
  { id: 'psyche', name: '16 Psyche', body: 'psyche', kind: 'asteroid', region: 'belt', gravity: 0.015, radiation: 450, illumination: 0.95, deposits: [metallic(2.3e16, 1.2)], features: [], node: 'psyche', description: 'A world of metal. Its iron alone could supply civilization for a million years.' },
  // --- Jupiter -----------------------------------------------------------
  { id: 'callisto', name: 'Callisto (Valhalla)', body: 'callisto', kind: 'surface', region: 'jupiter', gravity: 0.126, radiation: 36, illumination: 0.5, deposits: [icyMoon(1e17, 0.45), { type: 'carbonaceous', name: 'Dark silicate lag', reserve: 1e15, grade: 0.8, difficulty: 1.2, yields: { carbon: 0.03, iron: 0.08, silicon: 0.1, oxygen: 0.2, water: 0.1 } }], features: ['iceShell'], node: 'callisto', description: 'Outside the lethal radiation belts, Callisto is the Jovian system\'s safe harbour.' },
  { id: 'ganymede', name: 'Ganymede (Galileo Regio)', body: 'ganymede', kind: 'surface', region: 'jupiter', gravity: 0.146, radiation: 29000, illumination: 0.5, deposits: [icyMoon(1e17, 0.5), { type: 'minerals', name: 'Grooved-terrain silicates', reserve: 5e12, grade: 1, difficulty: 1.3, yields: { iron: 0.08, silicon: 0.1, sulfur: 0.02, oxygen: 0.2 } }], features: ['iceShell', 'ocean'], node: 'ganymede', description: 'A moon larger than Mercury with a protective magnetic field, but still bathed in dangerous radiation.' },
  { id: 'europa', name: 'Europa (Conamara Chaos)', body: 'europa', kind: 'surface', region: 'jupiter', gravity: 0.134, radiation: 2000000, illumination: 0.5, deposits: [icyMoon(3e18, 0.95), { type: 'minerals', name: 'Chaos-terrain salts', reserve: 1e11, grade: 1, difficulty: 1.4, yields: { sulfur: 0.05, lithium: 2e-5, phosphorus: 2e-4 } }], features: ['iceShell', 'ocean', 'biosignatureCandidate'], node: 'europa', description: 'Beneath 20 km of ice lies more liquid water than all of Earth\'s oceans. The surface dose kills in days.' },
  { id: 'io', name: 'Io (Loki Patera)', body: 'io', kind: 'surface', region: 'jupiter', gravity: 0.183, radiation: 13000000, illumination: 0.5, deposits: [{ type: 'sulfur', name: 'Volcanic sulfur and silicates', reserve: 1e16, grade: 1, difficulty: 1.3, yields: { sulfur: 0.35, silicon: 0.1, oxygen: 0.15, iron: 0.05 } }], features: ['volcanic', 'machinesOnly'], node: 'io', description: 'An inferno of sulfur volcanoes. Only hardened autonomous machines can work here.' },
  // --- Saturn ------------------------------------------------------------
  { id: 'titan', name: 'Titan (Kraken Mare)', body: 'titan', kind: 'surface', region: 'saturn', gravity: 0.138, radiation: 1, illumination: 0.01, deposits: [{ type: 'atmosphere', name: 'Nitrogen–methane atmosphere', reserve: 9e18, grade: 1, difficulty: 1, yields: { nitrogen: 0.95, carbon: 0.037, hydrogen: 0.012 } }, { type: 'hydrocarbon', name: 'Liquid methane-ethane seas', reserve: 1e14, grade: 1, difficulty: 1, yields: { carbon: 0.78, hydrogen: 0.22 } }, icyMoon(1e18, 0.9)], features: ['thickAir'], node: 'titan', description: 'The only moon with a thick atmosphere. Here you can walk without a pressure suit, wearing only warm clothing and a breathing mask.' },
  { id: 'enceladus', name: 'Enceladus (Tiger Stripes)', body: 'enceladus', kind: 'surface', region: 'saturn', gravity: 0.0113, radiation: 300, illumination: 0.5, deposits: [icyMoon(5e16, 0.95), { type: 'ice', name: 'Plume organics', reserve: 1e12, grade: 1, difficulty: 1.2, yields: { water: 0.9, carbon: 0.01, nitrogen: 0.01, phosphorus: 1e-4 } }], features: ['iceShell', 'ocean', 'biosignatureCandidate'], node: 'enceladus', description: 'Geysers of ocean water, salts and organics erupt from warm fractures near the south pole.' },
  { id: 'saturn_orbit', name: 'Saturn Scoop Platforms', body: 'saturn', kind: 'orbital', region: 'saturn', gravity: 0, radiation: 500, illumination: 0.8, deposits: [{ type: 'gasGiant', name: 'Deep hydrogen–helium atmosphere', reserve: 1e22, grade: 1, difficulty: 2, yields: { fusionFuel: 1e-5, hydrogen: 0.6 } }], features: ['gasGiant'], node: 'saturn_orbit', description: 'High-orbit processing platforms serviced by atmospheric scoop ships.' },
  // --- Outer system ------------------------------------------------------
  { id: 'uranus_orbit', name: 'Uranus Scoop Platforms', body: 'uranus', kind: 'orbital', region: 'outer', gravity: 0, radiation: 400, illumination: 0.8, deposits: [{ type: 'gasGiant', name: 'Hydrogen–helium–methane envelope', reserve: 1e21, grade: 1.3, difficulty: 1.7, yields: { fusionFuel: 1.4e-5, hydrogen: 0.55, carbon: 0.02 } }], features: ['gasGiant'], node: 'uranus_orbit', description: 'Uranus has the shallowest giant-planet gravity well, which makes it the cheapest large helium-3 source.' },
  { id: 'triton', name: 'Triton (Cantaloupe Terrain)', body: 'triton', kind: 'surface', region: 'outer', gravity: 0.08, radiation: 150, illumination: 0.5, deposits: [{ type: 'ice', name: 'Nitrogen and water ice', reserve: 1e17, grade: 1, difficulty: 1.1, yields: { nitrogen: 0.5, water: 0.4, carbon: 0.02 } }], features: ['iceShell', 'geysers'], node: 'triton', description: 'A frozen captured world at the edge of the planetary realm.' },
  { id: 'pluto', name: 'Pluto (Sputnik Planitia)', body: 'pluto', kind: 'surface', region: 'outer', gravity: 0.063, radiation: 250, illumination: 0.5, deposits: [{ type: 'ice', name: 'Nitrogen glaciers and water ice', reserve: 1e17, grade: 1, difficulty: 1.2, yields: { nitrogen: 0.45, water: 0.45, carbon: 0.03 } }], features: ['kuiperGateway'], node: 'pluto', description: 'A heart-shaped glacier of nitrogen ice, forty times farther from the Sun than Earth.' },
];

export const SITE: Record<string, SiteDef> = Object.fromEntries(SITES.map((s) => [s.id, s]));
